### ISSUE TITLE
I can't get sound to work on manjaro linux

### ISSUE THREAD

**Issue by n3ry7** [pauleve/docker-mtgo#100]
Everything is running fine except sound, I think it might be something to do with arch linux.

I read the previous threads on sound issues, but could not figure it out. I am using:

./run-mtgo --sound

What information could I provide to help fix this?

**Comment by pauleve** [comment]
Hi, sorry for the delay. Please do
```
./run-mtgo --update --sound &>output.log
```
and attach the file to a comment.

**Comment by Neryfoot** [comment]
No worries, thanks for the reply.

This is what I got.

[output.log](https://github.com/pauleve/docker-mtgo/files/5013081/output.log)

**Comment by pauleve** [comment]
Closing old inactive bugs. Feel free to reopen if still occurring with latest debug information.
