### ISSUE TITLE
Application cannot be started. Contact the application vendor.

### ISSUE THREAD

**Issue by space-potato** [pauleve/docker-mtgo#101]
Good morning,

Today the client stopped working with the error mentioned in the title. I'm not sure what the problem is, could it be an issue coming from WOTC's servers? The error log is the following (I'm using Fedora 32):

```

PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.81.0 built by: NETFXREL2
	clr.dll 			: 4.6.81.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.81.0 built by: NETFXREL2
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

SOURCES
	Deployment url			: http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application
						Server		: AkamaiNetStorage

IDENTITIES
	Deployment Identity		: MTGO.application, Version=3.4.116.4060, Culture=neutral, PublicKeyToken=80e21eca2a0e1258, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application resulted in exception. Following failure messages were detected:
		+ Value does not fall within the expected range.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [08/08/2020 08:58:04] : Activation of http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application has started.
	* [08/08/2020 08:58:05] : Processing of deployment manifest has successfully completed.

ERROR DETAILS
	Following errors were detected during this operation.
	* [08/08/2020 08:58:05] System.ArgumentException
		- Value does not fall within the expected range.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [08/08/2020 08:58:05]
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x0



```

**Comment by pauleve** [comment]
Hi, is it still occurring?

**Comment by orgcandman** [comment]
> PLATFORM VERSION INFO
> 	Windows 			: 6.1.7601.65536 (Win32NT)
> 	Common Language Runtime 	: 4.0.30319.42000
> 	System.Deployment.dll 		: 4.6.81.0 built by: NETFXREL2
> 	clr.dll 			: 4.6.81.0 built by: NETFXREL2
> 	dfdll.dll 			: 4.6.81.0 built by: NETFXREL2
> 	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)
> 
> SOURCES
> 	Deployment url			: http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application
> 
> ERROR SUMMARY
> 	Below is a summary of the errors, details of these errors are listed later in the log.
> 	* Activation of http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application resulted in exception. Following failure messages were detected:
> 		+ Downloading http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application did not succeed.
> 		+ The operation has timed out.
> 
> COMPONENT STORE TRANSACTION FAILURE SUMMARY
> 	No transaction error was detected.
> 
> WARNINGS
> 	There were no warnings during this operation.
> 
> OPERATION PROGRESS STATUS
> 	* [6/14/2021 4:06:05 PM] : Activation of http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application has started.
> 
> ERROR DETAILS
> 	Following errors were detected during this operation.
> 	* [6/14/2021 4:06:05 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
> 		- Downloading http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application did not succeed.
> 		- Source: System.Deployment
> 		- Stack trace:
> 			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
> 			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
> 			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
> 			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
> 			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
> 			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
> 			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
> 			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
> 		--- Inner Exception ---
> 		System.Net.WebException
> 		- The operation has timed out.
> 		- Source: System
> 		- Stack trace:
> 			at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
> 			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
> 
> COMPONENT STORE TRANSACTION DETAILS
> 	No transaction information is available.
> 

I get the following - seems like a "network error" - BUT:

wine@RHTPC1VM0NT:~$ curl http://mtgoclientdepot.onlinegaming.wizards.com/MTGO.application >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9835  100  9835    0     0  81958      0 --:--:-- --:--:-- --:--:-- 81958

I had an issue as well complaining about the .NET framework install, so I used winetricks inside the
container to install dotnet46, which succeeded.  Not sure how to debug further.  I'm running on Fedora 34 and using
docker.

**Comment by pauleve** [comment]
Can you try with
```
./run-mtgo panard/mtgo:2021-04-03
```
?
