### ISSUE TITLE
Window positioning bugs with wine 5.17 on Cinnamon

### ISSUE THREAD

**Issue by pauleve** [pauleve/docker-mtgo#108]
Follows up issue #104 
Upstream bug: https://bugs.winehq.org/show_bug.cgi?id=49779

**Comment by Greginator** [comment]
Using Cinnamon 4.6.7 (The most up to date 4.6 version, and the version used in Linux Mint prior to the January release of Cinnamon 4.8 in Linux Mint 20.1) this bug is **no longer present**.

I have **not** tested whether this bug is present in Linux Mint 20.1.

**Comment by pauleve** [comment]
I still get the issue with 4.6.7 on ubuntu... Finger crossed 4.8 will solve this

**Comment by Greginator** [comment]
The newest update has resurfaced this issue. I assume it's to do with the upgrade to 6.3.

**Comment by pauleve** [comment]
Probably, yes... The old image is available with
`./run-mtgo panard/mtgo:issue102`
hopefully, it still works with Cinnamon. A workaround would be to detect Cinnamon in the run-mtgo script and choose the right image accordingly; I add this to my TODO list :smile:

**Comment by pauleve** [comment]
For the record, the latest version of Cinnamon (and more precisely its window manager muffin) should fix this bug:
https://bugs.winehq.org/show_bug.cgi?id=50381
