### ISSUE TITLE
Error: unknown or unsupported macOS version: :mountain_lion

### ISSUE THREAD

**Issue by panSarin** [pauleve/docker-mtgo#109]
Hello, first I wanted to say: big thanks for doing such a usefull open source tool :)

Second: i got 
``` 
Error: unknown or unsupported macOS version: :mountain_lion
```
in xQuartz . 

Can it be related to that i still work on Mojave?

Last lines of stacktrace from bash are:
```
0061:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"
====== shutting down
wineserver -kw
```

**Comment by pauleve** [comment]
Hi, according to https://discourse.brew.sh/t/unknown-or-unsupported-macos-version-mountain-lion/8087 it seems that homebrew dropped support for old macOS versions some time ago...
You'll need to find a way to install XQuartz and others without homebrew.. 
For XQuartz, you may give a try to https://www.xquartz.org/; for the other dependencies (socat, gnu-getopt, wget), you may give a try to MacPorts https://www.macports.org/ https://stackoverflow.com/questions/16808543/install-socat-on-mac
Keep me in touch, and do not hesitate to post full output of the commands.

**Comment by pauleve** [comment]
In theory (I have no macOS), you can install MacPorts for Mojave using this link:
https://distfiles.macports.org/MacPorts/MacPorts-2.6.3-10.14-Mojave.pkg
and then the other dependencies than XQuartz can (probably) be installed using
```
sudo port install socat wget libgnugetopt
```

**Comment by panSarin** [comment]
I will try it, if there will be more troubles, I will just upgrade OsX version :)

**Comment by panSarin** [comment]
I updated osx to catalina and it works. There are some performance issues, but I assume that is normal in this approach. Again, thanks man!

**Comment by ny2292000** [comment]
I got that error while having OS Mojave on a Mac. So, I think this problem is still alive.

I tried the solution above and the initial error didn't go away when I tried to brew update.  The unsupported Mountain Lion error appeared when I tried brew doctor.

I will restart the computer to see if things change.

**Comment by pauleve** [comment]
Brew is no longer supported on Mojave, you should no longer use the `brew` command. If you cannot upgrade to a newer version, you'll need to try installing XQuartz and others manually, using the commands I posted in the previous comments.
Or install wine manually using https://github.com/pauleve/docker-mtgo/wiki/macOS:-installing-MTGO-using-Wine

**Comment by ny2292000** [comment]
Are you telling me that Brew no longer supports Mojave? Mojave is the penultimate Mac OS. The Big Sur is the latest one.
I can understand not supporting Mountain Lion, an 8-years old OS.
I am not complaining (since I am not a contributor to Homebrew).  I am just surprised.

**Comment by pauleve** [comment]
From the link I posted in my first comment, it may work on Mojave by doing
```
brew uninstall mongodb
```

**Comment by ny2292000** [comment]
Thanks.  It is working now.

**Comment by marcusconnor** [comment]
Does anyone know how to get it to install on Catalina. I got a bunch of errors when I tried to install it. It seems to think I'm running :lion

**Comment by melMass** [comment]
> Brew is no longer supported on Mojave

That's insane, does anybody know where I can read about it?

I have the same error under catalina while running any brew command even brew doctor:

```
Error: unknown or unsupported macOS version: :lion
```

**Comment by RodrigoZepeda** [comment]
I had the same error in Catalina worked with previous answer:
```
brew uninstall mongodb
```
I found it was installed (idk why) by doing 
```
brew list
```
