### ISSUE TITLE
Accessing Host File System?

### ISSUE THREAD

**Issue by JeffHoogland** [pauleve/docker-mtgo#11]
New to docker so this might be a docker thing more than an issue with this image - but is there an easy way to get access to my base file system through MTGO running in this docker image some how? Ideally I'd like to be able to import / export deck files.

**Comment by pauleve** [comment]
You have two options:
* either you can bind your host filesystem to the docker container by adding `-v /host/path:/container/path` to `run-mtgo` call ; `/mnt` or `/tmp/host` are examples of common container paths you may use.
* or, you can use `docker exec` to execute shell commands to transfer data from/to the container while it is running. For instance
```
docker exec mtgo_running cat mydeck.dek > mydeck.dek
```
will extract the file in /home/wine/mydeck.dek ; and
```
cat mydeck2.dek | docker exec -i mtgo_running tee mydeck2.dek >/dev/null
```
will import the file in the container (in /home/wine dir by default).

Here `mtgo_running` is the name of the container, which is set by `run-mtgo`.

Hope that helps!

**Comment by JeffHoogland** [comment]
Thank you!

**Comment by kylesnowschwartz** [comment]
Hi, I'm running into the same issue and having trouble understanding the commands necessary to move a deck I exported from MTGO onto my Ubuntu host machine. 

```
kyle@kyle-thinkpad:~$ touch tokens.txt
kyle@kyle-thinkpad:~$ cat tokens.txt | sudo docker exec -i mtgo_running tee tokens.txt >/dev/null
```
After running the following, my tokens.txt on my host machine is still an empty file. Am I misunderstanding the instructions?

I think the problem may be that the .txt files are being saved to `C:\users\wine\Desktop\tokens.txt` but I don't see how to save to `/home/wine` but I'm unsure. Thanks for any suggestions and thanks for this awesome project!

**Comment by JeffHoogland** [comment]
The easiest way to is modify the run-mtgo script. For example I added this to opts:

**-v /media/Storage:/mnt**

Which mounted me /media/Storage on my host system to /mnt on the docker image.

**Comment by pauleve** [comment]
Hi, I've updated my answer to makes things clearer.
If you want to go from docker to your computer, you should use the cat command (and from your computer to docker the tee command).
I think the /home/wine can be accessed by using "Desktop/My Documents" in the left pane when you browse files with MTGO ; correct me if I'm wrong and I'll update my answer (otherwise, "Desktop > / > home > wine).

**Comment by kylesnowschwartz** [comment]
Thanks @JeffHoogland, figured it out with the following command:

`sudo ./run-mtgo -v /home/kyle:/mnt`

Thanks for the suggestion.
