### ISSUE TITLE
Cannot connect to Docker daemon

### ISSUE THREAD

**Issue by kriv02** [pauleve/docker-mtgo#110]
On Manjaro, when I run ./run-mtgo, I get the following error message
`Cannot connect to the Docker daemon at unix:://var/run/docker.sock. Is the docker daemon running?`
I've added my user to the docker group like it says in the README, and restarted my computer, and it still gives the same message.

**Comment by pauleve** [comment]
You need to start the Docker daemon; if your distribution relies on systemd for instance, you need to do `systemctl start daemon` as root (and `systemctl enable docker` to start it automatically at boot)
