### ISSUE TITLE
Can't run mtgo on ubuntu - Application download did not succeed

### ISSUE THREAD

**Issue by guysz** [pauleve/docker-mtgo#113]
Hi,
I am trying to run MTGO on ubuntu with no success.
I only managed to run it once, the mtgo was installed and I could play the game.
Since then, each time I am trying to run mtgo I get the message:
"Application download did not succeed. Check your network connection, or contact your system administrator or network service provider"

Though I am sure I don't have network issue.
Here is the terminal log when I run with --debug flag:

docker run --privileged --rm -e DISPLAY -e WINEDEBUG= -v mtgo-data-guyszw:/home/wine/.wine/host/ -v mtgo-data-guyszw:/home/wine/.wine/drive_c/users/ -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /home/guyszw/.local/share/mtgo/Xauthority:/home/wine/.Xauthority:ro --net=host --ipc=host -e TZ=/usr/share/zoneinfo/Asia/Jerusalem --name mtgo_running panard/mtgo:latest mtgo
winetricks gdiplus=native sound=alsa winegstreamer=disabled wmp=disabled
Executing mkdir -p /home/wine
Using winetricks 20200412 - sha256sum: 40ff4c67804584b73d4d36153e1f64ca426d739f1790bd748f5ded0865e8cc7f with wine-5.12 and WINEARCH=win32
Using native override for following DLLs: gdiplus
Executing wine regedit C:windowsTemp_nativeoverride-dll.reg
Executing w_do_call sound=alsa
Executing mkdir -p /home/wine
Executing load_sound alsa
Setting sound driver to alsa
Executing wine regedit C:windowsTempset-sound.reg
Using override for following DLLs: winegstreamer
Executing wine regedit C:windowsTemp_disabledoverride-dll.reg
Using override for following DLLs: wmp
Executing wine regedit C:windowsTemp_disabledoverride-dll.reg
wineboot
wine /opt/mtgo/mtgo.exe
0128:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0128:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0128:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0128:fixme:advapi:LsaOpenPolicy ((null),0x31e608,0x00000001,0x31e5fc) stub
0128:fixme:security:GetWindowsAccountDomainSid (0031E578 009CB044 0031E574): semi-stub
0128:fixme:secur32:GetComputerObjectNameW NameFormat 7 not implemented
0128:fixme:advapi:LsaClose (0xcafe) stub
0128:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
0128:fixme:urlmon:DownloadBSC_OnProgress Unsupported status 3
0128:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0128:fixme:ntdll:EtwEventRegister ({319dc449-ada5-50f7-428e-957db6791668}, 10021925, 1006DBD0, 1006DBE8) stub.
0128:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 10002F3D, 28) stub
0128:fixme:sxs:SxsLookupClrGuid Ignored flags: 10000
0128:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040154 for dll L"mscoree.dll"
0128:err:ole:CoGetClassObject no class object {1e66f26b-79ee-11d2-8710-00c04f79ed0d} could be created for context 0x1
0128:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0128:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0128:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0128:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0138:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0128:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0128:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0138:fixme:ntdll:EtwEventRegister ({319dc449-ada5-50f7-428e-957db6791668}, 10021925, 1006DBD0, 1006DBE8) stub.
0138:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 10002F3D, 28) stub
0128:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0128:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0128:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0128:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0138:fixme:ntdll:EtwEventRegister ({319dc449-ada5-50f7-428e-957db6791668}, 00D575A8, 011D6470, 011D6488) stub.
0138:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00CC8861, 28) stub
0128:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0128:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0138:fixme:kernelbase:QuirkIsEnabled3 (0031F4C0, FFFFFFFF) stub!
0138:fixme:heap:GetNumaHighestNodeNumber semi-stub: 0031FBF8
0138:fixme:ntdll:EtwEventRegister ({e13c0d23-ccbc-4e12-931b-d9cc2eee27e4}, 00E56B5A, 011D5370, 011DEE60) stub.
0138:fixme:ntdll:EtwEventRegister ({763fd754-7086-4dfe-95eb-c01a46faf4ca}, 00E56B5A, 011D57B8, 011D6278) stub.
0138:fixme:ntdll:EtwEventRegister ({a669021c-c450-4609-a035-5af59af4df18}, 00E56B5A, 011DDB88, 011DEE70) stub.
0138:fixme:ntdll:EtwEventRegister ({cc2bcbba-16b6-4cf3-8990-d74c2e8af500}, 00E56B5A, 011D5458, 011D54C8) stub.
0138:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\windows\Microsoft.NET\Framework\v4.0.30319\mscordacwks.dll", 00B90000) stub
0128:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0128:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0138:fixme:path:parse_url failed to parse L"System.Deployment"
0138:fixme:path:parse_url failed to parse L"System.Security"
0138:fixme:path:parse_url failed to parse L"System.Xml"
0138:fixme:path:parse_url failed to parse L"System"
0138:fixme:path:parse_url failed to parse L"System.Configuration"
0128:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0128:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0138:fixme:path:parse_url failed to parse L"System.Windows.Forms"
0138:fixme:path:parse_url failed to parse L"System.Drawing"
0138:fixme:path:parse_url failed to parse L"System.Core"
0138:fixme:path:parse_url failed to parse L"System.Numerics"
0138:fixme:path:parse_url failed to parse L"System"
0138:fixme:path:parse_url failed to parse L"System.Core"
0138:fixme:path:parse_url failed to parse L"System.Windows.Forms"
0128:err:ole:create_server class {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} not registered
0128:err:ole:CoGetClassObject no class object {20fd4e26-8e0f-4f73-a0e0-f27b8c57be6f} could be created for context 0x4
0138:fixme:path:parse_url failed to parse L"Accessibility"
0138:fixme:path:parse_url failed to parse L"System.Runtime.Serialization.Formatters.Soap"
0138:fixme:path:parse_url failed to parse L"System.Drawing"
0138:fixme:nls:get_dummy_preferred_ui_language (0x8 0031EB24 00000000 0031EB20) returning a dummy value (current locale)
0138:fixme:nls:get_dummy_preferred_ui_language (0x8 0031EB24 0021C358 0031EB20) returning a dummy value (current locale)
0138:fixme:ntdll:EtwEventRegister ({8e9f5090-2d75-4d03-8a81-e5afbf85daf1}, 054E02E6, 00000000, 01674C00) stub.
0154:fixme:nls:LCIDToLocaleName unsupported flags 8000000
016c:fixme:sync:SetWaitableTimerEx (000001E0, 0609FEB8, 500, 00000000, 00000000, 00000000, 50) semi-stub
0128:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0168:fixme:ole:IiFTMUnknown_fnQueryInterface No interface for {00000144-0000-0000-c000-000000000046}.
0168:fixme:ole:IiFTMUnknown_fnQueryInterface No interface for {00000144-0000-0000-c000-000000000046}.
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x224: stub
0168:fixme:reg:RegDisableReflectionKey 0x224: stub
0168:fixme:reg:RegDisableReflectionKey 0x224: stub
0168:fixme:reg:RegDisableReflectionKey 0x224: stub
0168:fixme:reg:RegDisableReflectionKey 0x224: stub
0168:fixme:reg:RegDisableReflectionKey 0x224: stub
0168:fixme:reg:RegDisableReflectionKey 0x224: stub
0168:fixme:reg:RegDisableReflectionKey 0x224: stub
0168:fixme:reg:RegDisableReflectionKey 0x224: stub
0168:fixme:reg:RegDisableReflectionKey 0x228: stub
0168:fixme:reg:RegDisableReflectionKey 0x22c: stub
0168:fixme:reg:RegDisableReflectionKey 0x230: stub
0168:fixme:ole:IiFTMUnknown_fnQueryInterface No interface for {00000144-0000-0000-c000-000000000046}.
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x234: stub
0168:fixme:reg:RegDisableReflectionKey 0x234: stub
0168:fixme:reg:RegDisableReflectionKey 0x234: stub
0168:fixme:reg:RegDisableReflectionKey 0x234: stub
0168:fixme:reg:RegDisableReflectionKey 0x234: stub
0168:fixme:reg:RegDisableReflectionKey 0x234: stub
0168:fixme:reg:RegDisableReflectionKey 0x234: stub
0168:fixme:reg:RegDisableReflectionKey 0x234: stub
0168:fixme:reg:RegDisableReflectionKey 0x234: stub
0168:fixme:reg:RegDisableReflectionKey 0x238: stub
0168:fixme:reg:RegDisableReflectionKey 0x23c: stub
0168:fixme:reg:RegDisableReflectionKey 0x240: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x244: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x244: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x244: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x244: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x244: stub
0168:fixme:reg:RegDisableReflectionKey 0x248: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x220: stub
0168:fixme:reg:RegDisableReflectionKey 0x248: stub
0168:fixme:ole:IiFTMUnknown_fnQueryInterface No interface for {00000144-0000-0000-c000-000000000046}.
0168:fixme:path:parse_url failed to parse L"System.Configuration"
0168:fixme:path:parse_url failed to parse L"System.Xml"
0168:fixme:path:parse_url failed to parse L"System.Data.SqlXml"
0168:fixme:ras:RasEnumConnectionsW (061C4590,05F8F4CC,05F8F4D0),stub!
0168:fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
0168:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0168:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0168:fixme:ras:RasConnectionNotificationW (FFFFFFFF,000002B8,0x00000003),stub!
0168:fixme:nls:LCMapStringEx unsupported lparam b44fb0
0168:fixme:ntdll:EtwEventRegister ({38ed3633-5e3f-5989-bf25-f0b1b3318c9b}, 054E05BE, 00000000, 016ED910) stub.
0168:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 016ED8D0, 53) stub
0168:fixme:crypt:SystemFunction041 (0xb52a94, 10, 0): stub [RtlDecryptMemory]
0168:fixme:winsock:convert_aiflag_w2u Unhandled windows AI_xxx flags 0x20000
0168:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0168:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0168:fixme:winsock:convert_aiflag_w2u Unhandled windows AI_xxx flags 0x20000
0168:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0168:fixme:ver:GetCurrentPackageId (05F8DAA4 00000000): stub
0168:fixme:process:NtFlushProcessWriteBuffers stub

Help would be appreciated.
Thanks in advance.

**Comment by pauleve** [comment]
A new version of MTGO has been released one day ago which requires to reinstall it in a fresh environment.
Please try
```
./run-mtgo --reset
```
and keep me posted

**Comment by guysz** [comment]
--reset did solve the issue - many thanks!!
Weird that I'm pretty sure that I tried it already... nevermind.
Thanks for the quick repsonse!
