### ISSUE TITLE
./run-mtgo ate all my /root space

### ISSUE THREAD

**Issue by leonthoma** [pauleve/docker-mtgo#114]
Hey,
first up, thanks for your work ! UnfortunatelyI ran into some problems... 

I was following your instructions and tried to run MTGO (had about 1,5+ Gb of free space in /root) and it prompted that there was no space left and aborted. I can't find where all the downloaded files are and now root is full. Please help !

Thanks

**Comment by pauleve** [comment]
You need quite some disk space available, as there is both quite some space used by the docker image (~1.5GB) and MTGO itself (~1GB).
To cleanup everything, you may use
```sh
sudo docker volume rm mtgo-data-$USER  # remove MTGO files
sudo docker rmi panard/mtgo:latest   # remove Docker image
sudo docker system prune  # remove orphan images, and unclean containers, ..
```

**Comment by leonthoma** [comment]
Thanks so much for the very quick help ! Resolved everything. Maybe a little off topic now, but I'm curious why docker is using /root space and not /home..

**Comment by pauleve** [comment]
By default, everything goes into /var/lib/docker, but that can be changed (for instance for an external HD)
