### ISSUE TITLE
help wanted: change display resolution of mtgo?

### ISSUE THREAD

**Issue by kylesnowschwartz** [pauleve/docker-mtgo#12]
Almost in shock that MTGO is working beautifully on Ubuntu (17.10 64-bit) with this fantastic docker repo! 

I'm new to using docker and wine, is there a way to alter the resolution of the program running? even max-sized the cards are appearing quite small. Thank you again.

**Comment by pauleve** [comment]
You can use the `--winecfg` option of `run-mgo`: it will prompt a configuration tool before launching MTGO. There you go to Graphics tab, and you can adjust screen resolution, or even emulate a desktop (I think in your case the resolution should be enough).

**Comment by brianmadden** [comment]
Not to necro a closed issue, but after adjusting the resolution settings in the `winecfg` the chat windows in MTGO will not open. 

On a 4k monitor I set the DPI to 192 and was unable to interact with the CardHoarderBot at all. I had to reset the DPI to 96 to get the chat windows to open. 

Is anyone aware of a solution to this besides just resetting the DPI to 96?
