### ISSUE TITLE
Extracting MTGO Replays

### ISSUE THREAD

**Issue by cnalty** [pauleve/docker-mtgo#122]
I was attempting to pull my replays out of the docker for a project I'm working on. I saw #11 describe how to move files from the docker to the host system. However I can't seem to find the replay files. I know on windows these files are located in  C:\Users\<User>\AppData\Local\Apps\2.0\Data

I've tried exploring the file system by SSHing into the docker container. I guess I just don't really understand how the wine file system is laid out. It appears the only folder I can see with SSH, outside of stuff like lib, bin, etc. is the /home/wine folder described in #11 which is empty by default. I know they must exist somewhere, because you can still view your replays through MTGO in the docker container

**Comment by pauleve** [comment]
It shoud be in `/home/wine/.wine/drive_c/users/wine/...`

Instead of using ssh, you can use the command
```
docker exec -it mtgo_running bash
```
to open a shell in a running mtgo container.
There you can use the find command to locate your files and then use the `docker cp` command or alternatives.
