### ISSUE TITLE
HELP - "How to" for users with no experince using docker/wine and etc

### ISSUE THREAD

**Issue by pokegoload** [pauleve/docker-mtgo#13]
I know that I'm asking too much from you, but if you have time I would really appreciate some help. I have no experience using docker/wine and other but I have manage to get some parts of the tutorial done. 
I got stuck after "pulling" you docker and don't know who to proceed and have the image installed. 
I've tried a bunch of things and searched for an answer but as I said I have zero knowledge on codding and etc.

--- This was my last message in terminal after pulling:
latest: Pulling from panard/mtgo
Digest: sha256:ad46d8277cf41b3a44b8ad3bdf6152d45791b1691d7b7c8eaa0146a8623a87ee
Status: Image is up to date for panard/mtgo:latest

--- I tried to "run" the scipt I got the following message using docker:
Jonass-MacBook-Pro:~ alvimjc$ docker run run-mtgo
Unable to find image 'run-mtgo:latest' locally
docker: Error response from daemon: pull access denied for run-mtgo, repository does not exist or may require 'docker login'.
See 'docker run --help'.

--- Than I tried to run again with another command:
Jonass-MacBook-Pro:~ alvimjc$ docker run panard/mtgo
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting

Unhandled Exception: System.ComponentModel.Win32Exception: Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Deployment.Application.UserInterfaceForm.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.set_Visible(Boolean value)
   at System.Deployment.Application.SplashPiece.ShowSplash(Form parentForm)
   at System.Deployment.Application.SplashPiece..ctor(UserInterfaceForm parentForm, SplashInfo info)
   at System.Deployment.Application.UserInterfaceForm.InitializeContent()
   at System.Deployment.Application.UserInterfaceForm..ctor(ManualResetEvent readyEvent, SplashInfo splashInfo)
   at System.Deployment.Application.UserInterface.UIThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
wine: Unhandled exception 0xe0434352 in thread 47 at address 0x5140023:0x7b43c05c (thread 0047), starting debugger...
Can't attach process 0037: error 5
err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.

--- Also tried using wine and had the following:
Jonass-MacBook-Pro:~ alvimjc$ wine wget -O run-mtgo https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo
fixme:wer:WerSetFlags (2) stub!
fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
wine: Call from 0x7b4272e1 to unimplemented function mscoree.dll.CorIsLatestSvc, aborting
wine: Unimplemented function mscoree.dll.CorIsLatestSvc called at address 0x7b4272e1 (thread 001b), starting debugger...
err:module:import_dll Library MSVCR120_CLR0400.dll (which is needed by L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
fixme:service:scmdatabase_autostart_services Auto-start service L"clr_optimization_v4.0.30319_64" failed to start: 1053
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow The explorer process failed to start.
wine: cannot find L"C:\\windows\\system32\\wget.exe"

It's very likely that I'm doing something stupid and easy to sort and I'm sorry in advance. And as a piece of information, probably necessary, I'm using a Mac.

**Comment by pauleve** [comment]
Hi!
Yeah, probably wiki pages with complete tutorials would be useful.

Following the instructions on https://github.com/pauleve/docker-mtgo,
as you are on macOS, first you need to follow the steps indicated here:
https://github.com/pauleve/docker-mtgo#note-for-macos-users

Then, the script is installed by executing the following commands:
```
wget -O run-mtgo https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo
chmod +x run-mtgo
```
Then, you run it by doing 
```
./run-mtgo
```

**Comment by pokegoload** [comment]
Hello pauleve, 
I followed all the steps as indicated:
1st) brew cask install xquartz 
2nd) brew install socat gnu-getopt;
3rd) wine wget -O run-mtgo https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo

--- But I constiniusly get the following message:
Jonass-MacBook-Pro:~ alvimjc$ wine wget -O run-mtgo https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo
fixme:wer:WerSetFlags (2) stub!
fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
wine: Call from 0x7b4272e1 to unimplemented function mscoree.dll.CorIsLatestSvc, aborting
wine: Unimplemented function mscoree.dll.CorIsLatestSvc called at address 0x7b4272e1 (thread 001b), starting debugger...
err:module:import_dll Library MSVCR120_CLR0400.dll (which is needed by L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
fixme:service:scmdatabase_autostart_services Auto-start service L"clr_optimization_v4.0.30319_64" failed to start: 1053
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow The explorer process failed to start.
wine: cannot find L"C:\\windows\\system32\\wget.exe"
Jonass-MacBook-Pro:~ alvimjc$ 

Any solutions for a newbie? Again, reall sorry for the trouble.

**Comment by pauleve** [comment]
Why do you prefix your commands with wine? You do not need wine.

I've put a wiki page where the instructions can be read from top to bottom:
https://github.com/pauleve/docker-mtgo/wiki

**Comment by pokegoload** [comment]
Fantastic pauleve!
Having that Wiki is really good for beginners. 
I found what was one of my mistakes, just installing Homebrew wasn't enough and I need to manually install "wget" (brew install wget). 
After that I manage to install the script and run the installation. 
I think I'm making progress. Thank you very much. 

<img width="1679" alt="screen shot 2018-01-09 at 22 28 12" src="https://user-images.githubusercontent.com/20818917/34746605-84d99b5e-f58c-11e7-9bdd-8daaf28ecaa0.png">

**Comment by pauleve** [comment]
Good to know about wget, I'll add it to the  instructions.
