### ISSUE TITLE
Can't purchase from store via PayPal

### ISSUE THREAD

**Issue by toxygene** [pauleve/docker-mtgo#14]
Attempting to make purchases from the in-game store via PayPal is suppose to launch a browser window, but nothing happens.

**Comment by pauleve** [comment]
Please try with the latest docker image and run-mtgo script (docker pull panard/mtgo ; and re-download run-mtgo script from github). It should now open your default webbrowser.

**Comment by toxygene** [comment]
Confirmed fixed! Thank you!
