### ISSUE TITLE
Repeated unexpected traps (M1)

### ISSUE THREAD

**Issue by mbenzvi** [pauleve/docker-mtgo#142]
This is moving the issue I brought up in another thread to this one. To see original:

_Originally posted by @mbenzvi in https://github.com/pauleve/docker-mtgo/issues/138#issuecomment-975465578_

I ran the command:

`PATH=/opt/homebrew/Cellar/gnu-getopt/2.37.2/bin/:$PATH ./run-mtgo`

I have included the log for the issue:
[output-current-version.log](https://github.com/pauleve/docker-mtgo/files/7582335/output-current-version.log)

There seems to be a point where things break and I repeatedly get the issue `Got unexpected trap -1`

I also tried the older version using per recommendation:

`PATH=/opt/homebrew/Cellar/gnu-getopt/2.37.2/bin/:$PATH ./run-mtgo panard/mtgo:2021-07-24'

This got stuck on `uncaught target signal 11 (Segmentation fault) - core dumped` although also had the same error as the current version multiple times in the running.

[output-old-version.log](https://github.com/pauleve/docker-mtgo/files/7582360/output-old-version.log)

I have an M1 chip on OS big sur. Let me know if more information is needed.

**Comment by pauleve** [comment]
Apparently, on M1, docker falls back to `qemu` to emulate an intel architecture, which might cause troubles.
The only thing I can think of now is trying to change  line 9 of the run-mtgo script to
```sh
opts="--platform linux/amd64"
```

Btw, you can download the latest run-mtgo script and you won't need the PATH trick anymore (in theory).

**Comment by mbenzvi** [comment]
Thank you for the advice on downloading. I downloaded it, edited the command as per your recommendation and am running into something else (and the shorthand issue from before seemed to return). Here is the log file:

[output.log](https://github.com/pauleve/docker-mtgo/files/7582762/output.log)

**Comment by mbenzvi** [comment]
I downloaded and made the suggested change, but got the following error:

`WARNING: image with reference panard/mtgo was found but does not match the specified platform: wanted linux/amd64, actual: linux/386`

Log: [output-pre-386-fix.log](https://github.com/pauleve/docker-mtgo/files/7584340/output-pre-386-fix.log)


So i replaced the amd64 with 386 in the opts command of the `run-mtgo` file and then ran into a similar issue as before:

`qemu: uncaught target signal 11 (Segmentation fault) - core dumped` and then nothing happens and I need to kill it via `docker kill mtgo_running`

Log:  [output-post-386-fix.log](https://github.com/pauleve/docker-mtgo/files/7584346/output-post-386-fix.log)
