### ISSUE TITLE
Unimplemented function api-ms-win-core-winrt-roparameterized

### ISSUE THREAD

**Issue by phcerdan** [pauleve/docker-mtgo#15]
I am getting these messages, even though they don't seem to interfere with the play, I thought it was a good idea to report.
```
wine: Call from 0x7b43c05c to unimplemented function api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll.RoGetParameterizedTypeInstanceIID, aborting
```

**Comment by pauleve** [comment]
These message are harmless for MTGO. Anyway, they have disappeared with wine 3.0, which is the next release to be shipped by the docker image.
