### ISSUE TITLE
Pop-up boxes are transparent.

### ISSUE THREAD

**Issue by razzyc** [pauleve/docker-mtgo#150]
The pop-up boxes whenever selecting a deck, loading a match, or conceding/quitting the client are transparent. Some elements of the box will load when interacted with, however the majority of the pop-up will not load at all, unless moved to a different screen, or away from the main client window. When the full box does load it in it takes an exorbitant amount of time, and makes interacting with the client very unfriendly.

**Comment by pauleve** [comment]
Are you on macOS or Linux? Can you give a bit more information on your computer setup (OS version, graphics card, ...)
On macOS there are many issue reported with dialogs (e.g., #17 #135)
