### ISSUE TITLE
No longer starts, requires .NET 4.7.2

### ISSUE THREAD

**Issue by dorianbrown** [pauleve/docker-mtgo#151]
When trying to run `docker-mtgo`, as of this morning I get a pop-up with the following message
```
Unable to install or run this application. This application requires Version 4.7.2 Client or 
other compatible .NET Framework.

Please contact your system administrator.
```
It seems like a tweak to the winetweaks file is needed to get this working again.

**Comment by dorianbrown** [comment]
Trying to build an image with https://github.com/pauleve/docker-mtgo/blob/1856685a0a946a750f35421977f093e9f77371b5/Dockerfile#L32 changed to:
```sh
&& su - $WINE_USER -c 'taskset -c 0 winetricks -f -q dotnet472' \
```
Testing this change now.

**Comment by pauleve** [comment]
Thanks for the report. The new image now ships .NET 4.7.2 (#144)
```
./run-mtgo --update
```
might be enough, although running once `./run-mtgo --update --reset` might help.

**Comment by practual** [comment]
New image resolves the issue, thanks.

**Comment by dorianbrown** [comment]
Glad this was easily resolved, I'll close this issue.
