### ISSUE TITLE
.NET 4.7.2 never finishes installing

### ISSUE THREAD

**Issue by g0dnerd** [pauleve/docker-mtgo#154]
Hey, before the switch to .NET 4.7.2 MTGO ran just fine for me.
Now, the .NET install never finishes - as soon as the progress bar is full, it starts back over. I let it run for several hours to verify this.
I am running this on debian 10 with 32-bit winetricks.

**Comment by pauleve** [comment]
dotnet is already installed within the Docker image, so it should not trigger any installation of it. Unless you're trying to install it without docker?
In any case, you can post here the full console output so we can better spot the issue.

**Comment by jzak7** [comment]
I have the same issue.  Running the script brings up the install screen and then tries to install .NET 4.7.2 forever but never completes.  However, if I run it with the --test option, everything runs just fine with no install needed.

**Comment by pauleve** [comment]
You can try with the `--reset`option (only once), to properly reset the wine registry.

**Comment by Diceshake** [comment]
I am also experiencing this issue. 

@jzak7's solution of using `--test` worked - I did not try `--reset`

Great image though. Cheers!

**Comment by patdahl** [comment]
I also experienced this. `--reset` fixed the issue.

**Comment by g0dnerd** [comment]
I can confirm --reset fixes the issue. Thanks!
