### ISSUE TITLE
Opening "secondary" window causes freeze since Wine 7.10 upgrade

### ISSUE THREAD

**Issue by practual** [pauleve/docker-mtgo#156]
Since upgrading to Wine 7.10, any attempt to open a secondary window (for example, joining a league, editing a draft deck) causes the application to freeze immediately after the window appears, usually before the window has fully loaded.

Reverting back to Wine 7.7 (e.g. with `./run-mtgo.sh panard/mtgo:pr144`) resolves the issue.

Example debug output after clicking "edit deck" and prompting a new window to open:
```
0258:fixme:wtsapi:WTSQuerySessionInformationW Unimplemented class 8
0258:fixme:wtsapi:WTSRegisterSessionNotification Stub 0005004C 0x00000000
0258:fixme:msg:ChangeWindowMessageFilterEx 0005004C c056 1 0021E584
0258:fixme:msg:ChangeWindowMessageFilterEx 0005004C 111 1 0021E584
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
```

(not particularly helpful though, looks identical to a "healthy" build)
```
0258:fixme:wtsapi:WTSQuerySessionInformationW Unimplemented class 8
0258:fixme:wtsapi:WTSRegisterSessionNotification Stub 0005004C 0x00000000
0258:fixme:msg:ChangeWindowMessageFilterEx 0005004C c056 1 0021E584
0258:fixme:msg:ChangeWindowMessageFilterEx 0005004C 111 1 0021E584
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0258:fixme:nls:ResolveLocaleName stub: L"de", 00215A64, 85
0258:fixme:nls:ResolveLocaleName stub: L"ja", 00215A64, 85
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
052c:fixme:msg:ChangeWindowMessageFilter c059 00000001
052c:fixme:dwmapi:DwmAttachMilContent (0001009C) stub
0258:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
```

**Comment by pauleve** [comment]
thanks for the report. I reverted the default image to wine 7.7, the time to investigate.
Does it still happen with the emulate desktop mode (`./run-mtgo --winecfg` > Graphics > Emulate desktop)?

**Comment by practual** [comment]
> Does it still happen with the emulate desktop mode

Yes, it does.

**Comment by pauleve** [comment]
I tried the Wine 7.11 with `./run-mtgo.sh panard/mtgo:pr157` and had no issue. Can you give a try as well?

**Comment by practual** [comment]
No such luck I'm afraid. Any other debug info I can provide?

**Comment by pauleve** [comment]
Because newest version of wine make the login freeze much less frequent, I've merge wine 7.19.
If this issue is still occurring, you can use `./run-mtgo panard/mtgo:2022-04-29` to use wine 7.7.

**Comment by practual** [comment]
I have found that the latest release doesn't have the same problems as seen before - so happy to close the issue - thanks!
