### ISSUE TITLE
EULA and multi-monitor issue

### ISSUE THREAD

**Issue by JeffHoogland** [pauleve/docker-mtgo#16]
When MTGO updates you need to accept the EULA again. The problem is that when the EULA window opens itself on a different monitor from where MTGO's main window is opened it is simply greyed out garbage of other applications you current have open on that screen:

https://i.imgur.com/zxJ1Xxk.png

I can tell this is the EULA window because it is the correct shape.

The work around for the time being is turning off all but one of my monitors before launching MTGO for the first time after the update. This forces the EULA window to open over the main MTGO window so I can interact with it as expected.

**Comment by apetresc** [comment]
What is your window manager/compositor configuration like? I've never seen this particular problem before on my multi-monitor setup, although I do get black border artefacts if my compositor is disabled.

**Comment by JeffHoogland** [comment]
I am using a derivative of Enlightenment DR17 without compositing.

**Comment by pauleve** [comment]
You can try two different things:
* using winecfg (`./run-mtgo --winecfg`) you can select "emulate virtual desktop" (Graphics tab) ; you don't need to run winecfg each time, the setting is persistent.
* try using a test image which uses latest Wine 3.0: `./run-mtgo panard/mtgo:sound` 

Let me know what is working with you.

**Comment by JeffHoogland** [comment]
Virtual desktop lets this work as expected. Can close this I think.
