### ISSUE TITLE
[Question] Can I run this on M1 Macs?

### ISSUE THREAD

**Issue by whaler-ragweed** [pauleve/docker-mtgo#168]
I see some discussions here, but I'm not sure that if there is a way to run this docker on M1 Macs. I tried all ways that those discussions mentioned but still failed.

**Comment by pauleve** [comment]
Probably not at the moment. It might be that in the current of this year, Wine will support executing x86 apps on any platform, but this is still heavily experimental for now.

**Comment by whaler-ragweed** [comment]
> Probably not at the moment. It might be that in the current of this year, Wine will support executing x86 apps on any platform, but this is still heavily experimental for now.

Got it! I'm using UTM/Parallels to run MTGO, but the performance is not that good since my iMac only has 8 GB ram. Thank you for your contribution.

**Comment by pauleve** [comment]
See #188 for giving a try to running MTGO on M1.
