### ISSUE TITLE
Play Match hangs on highly populated leagues

### ISSUE THREAD

**Issue by Greginator** [pauleve/docker-mtgo#171]
When I attempt to press play match on a league from the main window, the separate window pops up and then hangs. The timer searching for a new match never increments and the program becomes unusable. This only seems to happen on highly populated leagues, such as pioneer or legacy. For example vintage loads correctly, the timer increments and I can play a match. Changing the number of CPUs or using emulate desktop didn't seem to make a difference either.
Potentially it has got a race condition loading the players in the list of the window would be my guess.

OS: Ubuntu Kinetic
Desktop environment (for Linux): Cinnamon
Graphics card: 1070ti
Docker Version: Docker version 23.0.2, build 569dd73

[output-play-match-freeze.log](https://github.com/pauleve/docker-mtgo/files/11116866/output-play-match-freeze.log)

**Comment by Greginator** [comment]
As an update this appears to be intermittent, I'm not sure what is causing it but I was able to get it to freeze up consistently when I posted this and now I have been able to use it fine for the past couple of days. I am happy for this to be closed for now but I can imagine this might come back in the future. I have had it happen on 2 different occasions since the most recent patch.

**Comment by cnalty** [comment]
I started having the same issue today. MTGO hangs whenever I try to open a league page, even if I do not hit 'play match'. Happening in legacy leagues for me. I've tried removing my docker data and reinstalling, but doesn't seem to help

**Comment by cnalty** [comment]
Update, leagues started working again for me. However, Resizing the game window (which starts quite small) at all generally causes a freeze up of mtgo, and even my entire system stops allowing me to click anywhere. Meaning I must alt-f4 and use the arrow keys to terminate process to close the program

**Comment by practual** [comment]
Still happening sporadically, seemingly out of the blue - haven't been able to join a league for a few days now:

![image](https://github.com/pauleve/docker-mtgo/assets/3340354/5f1e07be-9836-4b0f-8c96-4c019562ccba)

**Comment by practual** [comment]
Getting the same issue joining leagues with lower player counts as well:

![image](https://github.com/pauleve/docker-mtgo/assets/3340354/ba39ddf0-0a15-4ec3-89e2-ed9885b51ebe)

**Comment by cnalty** [comment]
I also started experiencing this a few days ago. I've been able to play a couple matches, but for the most part for the past week I have the same experience. I've tried deleting my mtgo volume, reinstalling the mtgo-docker, and restarting my machine, and updated the docker as well.

The debug output is just this on repeat when it hangs:

0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported sfnt font: embedded bitmap data.
0428:warn:font:unix_face_create unable to parse font, falling back to FreeType
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported sfnt font: embedded bitmap data.
0428:warn:font:unix_face_create unable to parse font, falling back to FreeType
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:new_ft_face Ignoring font "/opt/wine-devel/share/wine/fonts/vgafix.fon"/0xf7f3f000
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:new_ft_face Ignoring font "/opt/wine-devel/share/wine/fonts/vgas1255.fon"/0xf7f3f000
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:new_ft_face Ignoring font "/opt/wine-devel/share/wine/fonts/vgas1256.fon"/0xf7f3f000
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:new_ft_face Ignoring font "/opt/wine-devel/share/wine/fonts/vgas1257.fon"/0xf7f3f000
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:new_ft_face Ignoring font "/opt/wine-devel/share/wine/fonts/vgas874.fon"/0xf7f3f000
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:new_ft_face Ignoring font "/opt/wine-devel/share/wine/fonts/vgasys.fon"/0xf7f3f000
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:new_ft_face Ignoring font "/opt/wine-devel/share/wine/fonts/vgasyse.fon"/0xf7f3f000
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:new_ft_face Ignoring font "/opt/wine-devel/share/wine/fonts/vgasysg.fon"/0xf7f3f000
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:new_ft_face Ignoring font "/opt/wine-devel/share/wine/fonts/vgasysr.fon"/0xf7f3f000
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:new_ft_face Ignoring font "/opt/wine-devel/share/wine/fonts/vgasyst.fon"/0xf7f3f000
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:unix_face_create unable to parse font, falling back to FreeType
0428:warn:font:ft_face_get_full_name full name not found, using L"Courier Regular" instead
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:unix_face_create unable to parse font, falling back to FreeType
0428:warn:font:ft_face_get_full_name full name not found, using L"MS Sans Serif Regular" instead
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:unix_face_create unable to parse font, falling back to FreeType
0428:warn:font:ft_face_get_full_name full name not found, using L"MS Sans Serif Regular" instead
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:unix_face_create unable to parse font, falling back to FreeType
0428:warn:font:ft_face_get_full_name full name not found, using L"MS Sans Serif Regular" instead
0428:warn:font:opentype_get_ttc_sfnt_v1 unsupported font format 10d5a4d
0428:warn:font:unix_face_create unable to parse font, falling back to FreeType
0428:warn:font:ft_face_get_full_name full name not found, using L"Small Fonts Regular" instead
0428:warn:msvcrt:_configure_wide_argv (1) stub
0428:warn:msvcrt:_initialize_wide_environment stub
0428:warn:file:NtQueryAttributesFile L"\\??\\C:\\winedbg.exe" not found (c0000034)
0430:warn:globalmem:KernelBaseGetGlobalData semi-stub!
0430:warn:console:console_ioctl Incorrect access to Shell-no-window console (ioctl=50403c)
0430:warn:console:console_ioctl Incorrect access to Shell-no-window console (ioctl=50403c)
0430:warn:console:console_ioctl Incorrect access to Shell-no-window console (ioctl=508048)

**Comment by pauleve** [comment]
Thanks for the debug. Yesterday I've updated the image to wine 8.10, have you tried with `./run-mtgo --update` since?

I'll look into this console error and give a try to a league tonight.

**Comment by cnalty** [comment]
I have updated to the latest. It looks like this is the actual debug output I get when clicking 'play match'. It is followed by the repeating error above until I terminate the process

0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\en-US\\GameDetails.resources.dll" not found (c000003a)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\en-US\\GameDetails.resources\\GameDetails.resources.dll" not found (c000003a)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\en-US\\GameDetails.resources.exe" not found (c000003a)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\en-US\\GameDetails.resources\\GameDetails.resources.exe" not found (c000003a)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\en\\GameDetails.resources.dll" not found (c000003a)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\en\\GameDetails.resources\\GameDetails.resources.dll" not found (c000003a)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\en\\GameDetails.resources.exe" not found (c000003a)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\en\\GameDetails.resources\\GameDetails.resources.exe" not found (c000003a)
0234:warn:file:get_mountmgr_fs_info failed to retrieve filesystem type from mountmgr, status 0xc000000e
0234:warn:module:find_builtin_dll cannot find builtin library for L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\WotC.MtGO.Client.Common.Collections.dll"
0234:warn:module:find_builtin_dll cannot find builtin library for L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\WotC.MtGO.Client.Common.Collections.dll"
0234:warn:file:NtCreateFile L"\\??\\C:\\windows\\assembly\\NativeImages_v4.0.30319_32\\WotC.MtGO.C75a14d8a#\\" not found (c0000034)
0234:warn:file:NtCreateFile L"\\??\\C:\\windows\\assembly\\NativeImages_v4.0.30319_32\\WotC.MtGO.C75a14d8a#\\" not found (c0000034)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\NQ65PRBP.YL6\\OQ0NNY58.XMJ\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\WotC.MtGO.Client.Common.Collections.INI" not found (c0000034)
0234:fixme:wtsapi:WTSQuerySessionInformationW Unimplemented class 8
0234:fixme:wtsapi:WTSRegisterSessionNotification Stub 00050094 0x00000000
0234:fixme:msg:ChangeWindowMessageFilterEx 00050094 c053 1 0031EC74
0234:fixme:msg:ChangeWindowMessageFilterEx 00050094 111 1 0031EC74
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:NtCreateFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\Data\\GDJXP7TG.Y7N\\X96ZXR1T.H99\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\Data\\3.4.133.4366\\4saogaei.newcfg" not found (c0000034)
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:NtCreateFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\Data\\GDJXP7TG.Y7N\\X96ZXR1T.H99\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\Data\\3.4.133.4366\\gjg4ctuz.newcfg" not found (c0000034)
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:NtCreateFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\Data\\GDJXP7TG.Y7N\\X96ZXR1T.H99\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\Data\\3.4.133.4366\\l3aiblkl.newcfg" not found (c0000034)
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:NtCreateFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\Data\\GDJXP7TG.Y7N\\X96ZXR1T.H99\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\Data\\3.4.133.4366\\sv1um04d.newcfg" not found (c0000034)
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:NtCreateFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\Data\\GDJXP7TG.Y7N\\X96ZXR1T.H99\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\Data\\3.4.133.4366\\dzmrfyxq.newcfg" not found (c0000034)
0234:warn:wincodecs:png_decoder_initialize no pHYs block present
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:ole:enter_apartment Attempt to change threading model of this apartment from apartment threaded to multi-threaded
0234:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0234:warn:ole:enter_apartment Attempt to change threading model of this apartment from apartment threaded to multi-threaded
0234:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0234:warn:ole:enter_apartment Attempt to change threading model of this apartment from apartment threaded to multi-threaded
0234:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0234:warn:ole:enter_apartment Attempt to change threading model of this apartment from apartment threaded to multi-threaded
0234:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0234:warn:wincodecs:png_decoder_initialize no pHYs block present
0234:warn:wincodecs:png_decoder_initialize no pHYs block present
0234:warn:wincodecs:png_decoder_initialize no pHYs block present
0234:warn:wincodecs:png_decoder_initialize no pHYs block present
0234:warn:wincodecs:png_decoder_initialize no pHYs block present
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\windows\\assembly\\GAC_32" not found (c0000034)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\windows\\assembly\\GAC_MSIL" not found (c0000034)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\windows\\assembly\\GAC" not found (c0000034)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\windows\\Microsoft.Net\\assembly\\GAC_32\\policy.4.0.Microsoft.CSharp" not found (c0000034)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\windows\\Microsoft.Net\\assembly\\GAC_MSIL\\policy.4.0.Microsoft.CSharp" not found (c0000034)
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\windows\\Microsoft.Net\\assembly\\GAC" not found (c0000034)
0234:warn:file:NtQueryFullAttributesFile L"\\??\\C:\\windows\\Microsoft.Net\\assembly\\GAC_32\\Microsoft.CSharp\\v4.0_4.0.0.0__b03f5f7f11d50a3a\\Microsoft.CSharp.dll" not found (c000003a)
0234:warn:file:NtCreateFile L"\\??\\C:\\windows\\assembly\\NativeImages_v4.0.30319_32\\Microsoft.CSharp\\" not found (c0000034)
0234:warn:file:NtCreateFile L"\\??\\C:\\windows\\assembly\\NativeImages_v4.0.30319_32\\Microsoft.CSharp\\" not found (c0000034)
0234:warn:module:find_builtin_dll cannot find builtin library for L"\\??\\C:\\windows\\Microsoft.Net\\assembly\\GAC_MSIL\\Microsoft.CSharp\\v4.0_4.0.0.0__b03f5f7f11d50a3a\\Microsoft.CSharp.dll"
0234:warn:module:find_builtin_dll cannot find builtin library for L"\\??\\C:\\windows\\Microsoft.Net\\assembly\\GAC_MSIL\\Microsoft.CSharp\\v4.0_4.0.0.0__b03f5f7f11d50a3a\\Microsoft.CSharp.dll"
0234:warn:file:NtQueryAttributesFile L"\\??\\C:\\windows\\Microsoft.Net\\assembly\\GAC_MSIL\\Microsoft.CSharp\\v4.0_4.0.0.0__b03f5f7f11d50a3a\\Microsoft.CSharp.INI" not found (c0000034)
0234:warn:module:find_builtin_dll cannot find builtin library for L"\\??\\C:\\windows\\Microsoft.Net\\assembly\\GAC_MSIL\\Microsoft.CSharp\\v4.0_4.0.0.0__b03f5f7f11d50a3a\\Microsoft.CSharp.dll"
0234:warn:module:find_builtin_dll cannot find builtin library for L"\\??\\C:\\windows\\Microsoft.Net\\assembly\\GAC_MSIL\\Microsoft.CSharp\\v4.0_4.0.0.0__b03f5f7f11d50a3a\\Microsoft.CSharp.dll"
0234:warn:seh:dispatch_exception unknown exception (code=e0434352) raised
0234:warn:ole:enter_apartment Attempt to change threading model of this apartment from apartment threaded to multi-threaded
0234:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0234:warn:ole:enter_apartment Attempt to change threading model of this apartment from apartment threaded to multi-threaded
0234:fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
0234:warn:seh:OutputDebugStringA "DeckFilterFacade:BuildFilteredResults(): 0ms\r\n"
0234:warn:seh:dispatch_exception "DeckFilterFacade:BuildFilteredResults(): 0ms\r\n"
0234:fixme:wtsapi:WTSQuerySessionInformationW Unimplemented class 8
0234:fixme:wtsapi:WTSRegisterSessionNotification Stub 000100CC 0x00000000
0234:fixme:msg:ChangeWindowMessageFilterEx 000100CC c053 1 0031EBA4
0234:fixme:msg:ChangeWindowMessageFilterEx 000100CC 111 1 0031EBA4
0234:warn:seh:OutputDebugStringA "CardGroupingViewModel.ApplyFilterResults: 0ms\r\n"
0234:warn:seh:dispatch_exception "CardGroupingViewModel.ApplyFilterResults: 0ms\r\n"
0234:warn:seh:OutputDebugStringA "CardGroupingViewModel.ApplyFilterResults: 0ms\r\n"
0234:warn:seh:dispatch_exception "CardGroupingViewModel.ApplyFilterResults: 0ms\r\n"
0234:warn:seh:OutputDebugStringA "DeckFilterFacade:BuildFilteredResults(): 0ms\r\n"
0234:warn:seh:dispatch_exception "DeckFilterFacade:BuildFilteredResults(): 0ms\r\n"
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:fd_set_file_info Failed to set extended attribute user.DOSATTRIB. errno 61 (No data available)
0234:warn:file:NtCreateFile L"\\??\\C:\\users\\wine\\AppData\\Local\\Apps\\2.0\\Data\\GDJXP7TG.Y7N\\X96ZXR1T.H99\\mtgo..tion_80b7d5223ec4322a_0003.0004_2569903e7ec5e0fe\\Data\\3.4.133.4366\\14afv4op.newcfg" not found (c0000034)
0234:warn:seh:OutputDebugStringA "CardGroupingViewModel.ApplyFilterResults: 0ms\r\n"
0234:warn:seh:dispatch_exception "CardGroupingViewModel.ApplyFilterResults: 0ms\r\n"
0234:warn:seh:OutputDebugStringA "CardGroupingViewModel.ApplyFilterResults: 0ms\r\n"
0234:warn:seh:dispatch_exception "CardGroupingViewModel.ApplyFilterResults: 0ms\r\n"
03dc:warn:file:NtCreateFile L"\\??\\C:\\windows\\system32\\start.exe.manifest" not found (c0000034)
03dc:warn:globalmem:KernelBaseGetGlobalData semi-stub!

**Comment by practual** [comment]
I am actually able to enter matches again - not sure if that's coincidence because I did try with your wine 8.10 image a few days ago with no success.

**Comment by pauleve** [comment]
Good to hear. Probably a coincidence, though...
Leagues ends in <48h, so I prefer not enrolling in one until then, sorry...
However, I also get most of the warnings of the debug of https://github.com/pauleve/docker-mtgo/issues/171#issuecomment-1596189288  when playing matches outside of leagues, so they're probably harmless.
Are you able to play tournament practices/open play games?
If it is a race condition, `--limit-cpus 1` might help in some cases  (or 8, just to give a chance to the scheduler... it is 4 by default)

**Comment by cnalty** [comment]
Setting num_cpus in the run file to 1, or using --limit-cpus 1 does not prevent joining a league queue freezing. I've also waited several minutes to see if it was a temporary freeze, but it does not unfreeze.

Playing games in tournament practice works fine for me.

**Comment by pauleve** [comment]
Just to be sure, can you try with an older image?
`./run-mtgo panard/mtgo:wine-8.2` or even `./run-mtgo panard/mtgo:wine-7.19`? you might need to do a `--reset` if it fails to launch..

**Comment by cnalty** [comment]
Both of those versions still freeze on trying to play a league match

**Comment by cnalty** [comment]
I know it has only been a couple weeks, but an update on my end is that is has gone from a intermittent problem, to permanent. I have only managed to play 3 league games in a single day in the past 3 weeks, trying every day. Other events work fine, including prelims, challenges, qualifiers, etc. It is only a problem with league queues, no matter the format for me.

Things I've tried:

- older images, including 8.2 and 7.19 as suggested
- resetting my docker database
- using n_cpus=1
- updating all my system packages and drivers
- reinstalling the docker image entirely
- various wine configs, including windows versions 7 through 11, with and without virtual desktop
- waiting as long as about 10 minutes to see if mtgo ever unfreezes after clicking 'play match'

**Comment by practual** [comment]
I've been using Wine directly with a lot of success:

- Download Wine for my linux distro: https://wiki.winehq.org/Download
- Download winetricks: https://wiki.winehq.org/Winetricks
- Install some packages with winetricks: `WINEARCH=win32 winetricks -q dotnet48 corefonts`
- Download the MTGO setup.exe: `https://mtgo.patch.daybreakgames.com/patch/mtg/live/client/setup.exe?v=8`
- Run with wine: `wine setup.exe`

**Comment by pauleve** [comment]
Thanks for this feedback. My schedule is over busy these days, haven't been able to play a single match since a while.. I hope it will change soon.
Anyway, if the above instructions work, the Docker image is different from two aspects: it uses dotnet472 and has no sound enabled.
Sound can be enabled with  `./run-mtgo --sound`, 
and dotnet48 can be tried with `./run-mtgo panard/mtgo:pr178` in a couple of hours from now (#178).

**Comment by practual** [comment]
I've also got an instance working inside a docker container, using a stripped back Dockerfile:
```
FROM i386/debian:stable

RUN apt update && apt install -y build-essential wget cabextract

RUN wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key

RUN wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/debian/dists/bookworm/winehq-bookworm.sources

RUN apt update && apt install -y --install-recommends winehq-stable

ADD --chmod=755 https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks /usr/local/bin/winetricks

RUN useradd -u 1000 -d /home/wine -m -s /bin/bash wine
WORKDIR /home/wine
USER wine
ENV WINEPREFIX /home/wine/.wine
ENV WINEARCH win32

RUN winetricks -q dotnet48 corefonts

ADD --chown=wine:wine https://mtgo.patch.daybreakgames.com/patch/mtg/live/client/setup.exe?v=8 /opt/mtgo/mtgo.exe

CMD winetricks sound=alsa renderer=gdi gdiplus=builtin winegstreamer=disabled wmp=disabled && wine /opt/mtgo/mtgo.exe && while :; do sleep 5; done
```
Build with `docker build .` and then run with (replacing `<image>` with the built image ID):
`docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.Xauthority:/root/.Xauthority --net=host <image>`

My next step is to build back up to the full Dockerfile and run scripts, and see where things go wrong.

**Comment by cnalty** [comment]
Confirm that #178  works

**Comment by pauleve** [comment]
Awesome news, I'll merge it to the default image today then.
