### ISSUE TITLE
Repeated relocate_ntdll errors

### ISSUE THREAD

**Issue by MakerOfDopamine** [pauleve/docker-mtgo#172]
After launch, Docker repeatedly prints the following line: 
"2023-03-31 12:15:46 00e0:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f310000), expect trouble"

OS: MacOS M1
Graphics card: M1
Output of `docker info`:

output.log
[output.log](https://github.com/pauleve/docker-mtgo/files/11118108/output.log)

**Comment by pauleve** [comment]
See #188 for giving a try to M1 support.
