### ISSUE TITLE
mac os: XQuartz does not open? 

### ISSUE THREAD

**Issue by kingdododo** [pauleve/docker-mtgo#19]
The first time I went through the instructions and ran ./run-mtgo, xquartz opend with "bash-3.2$", but nothing else would happen. So I rebooted, ran the command again, and now the xquartz opens, but no windows pop up and the following error message pops up on terminal: 

open -a XQuartz
socat on 10.123.86.119 forwarding to /private/tmp/com.apple.launchd.h7ddC3NbBK/org.macosforge.xquartz:0
2018/02/10 01:22:03 socat[795] E bind(5, {LEN=16 AF=2 10.123.86.119:6000}, 16): Address already in use
docker run --privileged --rm -e DISPLAY -v /Users/alexhwang/.local/share/mtgo:/home/wine/.wine/host/ -v mtgo-data:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/America/Los_Angeles --name mtgo_running panard/mtgo:latest mtgo
docker: Error response from daemon: Conflict. The container name "/mtgo_running" is already in use by container "208d561d7b61bcf48d26c00fb134249a4dccbc5313bd612777a96466ed7199a0". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'

Don't really know what I've done wrong, so :(

**Comment by pauleve** [comment]
You can try doing `docker rm -f mtgo_running` and `killall socat`, then try again.
