### ISSUE TITLE
Line 124: Docker not found 

### ISSUE THREAD

**Issue by adanlaj** [pauleve/docker-mtgo#20]
Hi, I'm fairly new at this, I've made it through adding homebrew and wine.  However, I am running into a problem.  I keep on getting "./run-mtgo: line 124: docker: command not found" and mtgo doesn't start up.  Do you have any advice with what to do? I've included what happens after I run "./run-mtgo"

Thanks in advance for your help.

 [User]$ ./run-mtgo
docker volume create mtgo-data
./run-mtgo: line 124: docker: command not found
Using network interface 'en1'
open -a XQuartz
socat on 192.168.0.6 forwarding to /private/tmp/com.apple.launchd.ij0iCMcOnr/org.macosforge.xquartz:0
2018/02/21 20:23:34 socat[13442] E bind(5, {LEN=16 AF=2 192.168.0.6:6000}, 16): Address already in use
docker run --privileged --rm -e DISPLAY -v /Users/Adan/.local/share/mtgo:/home/wine/.wine/host/ -v mtgo-data:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/America/Los_Angeles --name mtgo_running panard/mtgo:latest mtgo
./run-mtgo: line 124: docker: command not found

**Comment by pauleve** [comment]
Hi,
For this project, you do not need to install wine but docker. See 
https://github.com/pauleve/docker-mtgo/wiki/How-to-run-docker-image-for-MTGO-on-Linux-and-macOS

**Comment by adanlaj** [comment]
Hi, thanks for pointing my to the link.  I've uninstalled Wine and am still getting the same error when I run the docker script.  XQuartz opens up but doesn't seem to do anything. Can you give me any more advice? 

Here's the terminal output.

Luiss-MacBook-Pro:~ Adan$ wget -O run-mtgo https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo
--2018-02-22 18:44:13--  https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6310 (6.2K) [text/plain]
Saving to: ‘run-mtgo’

run-mtgo            100%[===================>]   6.16K  --.-KB/s    in 0s      

2018-02-22 18:44:14 (15.5 MB/s) - ‘run-mtgo’ saved [6310/6310]

Luiss-MacBook-Pro:~ Adan$ chmod +x run-mtgo
Luiss-MacBook-Pro:~ Adan$ chmod +x run-mtgo
Luiss-MacBook-Pro:~ Adan$ ./run-mtgo
docker volume create mtgo-data
./run-mtgo: line 124: docker: command not found
Using network interface 'en1'
open -a XQuartz
socat on 192.168.0.6 forwarding to /private/tmp/com.apple.launchd.ij0iCMcOnr/org.macosforge.xquartz:0
2018/02/22 18:45:05 socat[14047] E bind(5, {LEN=16 AF=2 192.168.0.6:6000}, 16): Address already in use
docker run --privileged --rm -e DISPLAY -v /Users/Adan/.local/share/mtgo:/home/wine/.wine/host/ -v mtgo-data:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/America/Los_Angeles --name mtgo_running panard/mtgo:latest mtgo
./run-mtgo: line 124: docker: command not found
Luiss-MacBook-Pro:~ Adan$

**Comment by Xarnithru** [comment]
Hey, I've got the same thing happening, went through the described steps of installing homebrew and docker but received the line 124: docker: command not found error.

**Comment by pauleve** [comment]
As written in the documentation, you need to install docker.

**Comment by Xarnithru** [comment]
Thanks for the reply. Once I have docker, will I need to repeat the instructions, or will it work without doing so? Any uninstall necessary, now that I've done the steps you outlined, but without first installing docker?

**Comment by Xarnithru** [comment]
Got it up and running, thank you!
