### ISSUE TITLE
Quartz opening but without showing MOL

### ISSUE THREAD

**Issue by carlostiberiojr** [pauleve/docker-mtgo#21]
Hi guys, 

I have this strange output of the console, when I try to run the docker image:

TiberioMacBookPro:~ carlostiberiojr$ ./run-mtgo 
Using network interface 'en1'
open -a XQuartz
socat on 192.168.1.14 forwarding to /private/tmp/com.apple.launchd.1cx72bdCia/org.macosforge.xquartz:0
docker run --privileged --rm -e DISPLAY -v /Users/carlostiberiojr/.local/share/mtgo:/home/wine/.wine/host/ -v mtgo-data:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/zoneinfo/America/Sao_Paulo --name mtgo_running -o mtgo
unknown shorthand flag: 'o' in -o
See 'docker run --help'.
./run-mtgo: line 230:   704 Terminated: 15          tail -f ${URL_REQUESTS}
       706                       | while read url; do
    run $WEBBROWSER "${url}";
done

This -o things is bugging me... and I don't know what could be the issue here...

Thanks in advance !

**Comment by pauleve** [comment]
It looks like the command `getopt` is not the one expected. Do you have it installed with homebrew? (`brew install gnu-getopt`) ; the script looks for `/usr/local/opt/gnu-getopt/bin/getopt` can you check it exists? (`ls -l /usr/local/opt/gnu-getopt/bin/getopt`)

In the worst case, simply replace line 55 with `args="${@}"` to disable option verification.

If it works, please let me know if you experience issue #17 with black windows on macOS (and if so, please try the two last the two last comments).

**Comment by carlostiberiojr** [comment]
Thanks for the quick answer ! 

Missing gnu-getopt was the really issue here.
I think we can update the README, to have the line:

**brew install socat gnu-getopt**

changed to

**brew install socat
brew install gnu-getopt**

as, for some reason, both together, didn't trigger correctly.

Thanks a lot ! I have everything working fine now... just will fix some size issues :D

**Comment by tyrosario** [comment]
Hi @pauleve 
I'm trying to run your mtgo docker container from my M1 macbook air, but I'm seeing a similar issue. The script will run and it will say that the docker container is up and running, but MTGO never opens. An XQuartz terminal will open, though. How can I fix this? I have socat and gnu-getopt installed on my machine. I have attached a file containing the output from the ./run-mtgo script.

[run_mtgo_output.txt](https://github.com/user-attachments/files/18564584/run_mtgo_output.txt)
