### ISSUE TITLE
 mtgo doesnt open macos

### ISSUE THREAD

**Issue by kenshaozinho** [pauleve/docker-mtgo#23]
Hi, im a bit of a newbie and just followed all the steps, but after all of that I'm getting these errors:

./run-mtgo 
docker volume create mtgo-data
./run-mtgo: line 124: docker: command not found
Using network interface 'en0'
open -a XQuartz
socat on 192.168.1.105 forwarding to /private/tmp/com.apple.launchd.XOqLSMw2hO/org.macosforge.xquartz:0
docker run --privileged --rm -e DISPLAY -v /Users/fofinhos/.local/share/mtgo:/home/wine/.wine/host/ -v mtgo-data:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/zoneinfo/America/Bogota --name mtgo_running panard/mtgo:latest mtgo
./run-mtgo: line 124: docker: command not found
./run-mtgo: line 230:   754 Terminated: 15          tail -f ${URL_REQUESTS}
       756                       | while read url; do
    run $WEBBROWSER "${url}";
done
MacBook-Pro-de-Fofinhos:~ fofinhos$ 

Any idea in what i could be missing??

**Comment by theli-ua** [comment]
It looks like you're missing Docker (its a common for all platforms  prerequisite stated in the README)
https://www.docker.com/community-edition#/download

**Comment by kenshaozinho** [comment]
thanks, you're correct. I did all the cli steps but completely missed the docker installation.

now it kinda loads, but I got a message and a crash that ends with this

wine: Unhandled page fault on read access to 0x00000018 at address 0x7ed33a8a (thread 001b), starting debugger...

**Comment by kenshaozinho** [comment]
just did a --reset and it works now!
