### ISSUE TITLE
Docker doesn't work

### ISSUE THREAD

**Issue by qsdf99** [pauleve/docker-mtgo#26]
When i launch docker, the whale logo appears in the top right. Then as shown of the screenshot, it says docker is starting, but it stays like that and doesn't actually start, so ./run-mtgo doesn't work.
![capture d ecran 2018-05-01 a 23 21 05](https://user-images.githubusercontent.com/38894632/39494353-5f89e838-4d96-11e8-886f-024c292eb313.png)

**Comment by pauleve** [comment]
If Docker is still any issue, you can follow the step-by-step tutorial to install MTGO on macOS without Docker available here:
https://github.com/pauleve/docker-mtgo/wiki/macOS:-installing-MTGO-using-Wine
