### ISSUE TITLE
Experience serious spikes trying to play MODO on Magic Online

### ISSUE THREAD

**Issue by Xukinorris** [pauleve/docker-mtgo#27]
Pretty much the title of the issue, has anyone had the same problem?

Many portions of the screen simply do not load (remains all black) and the parts that load take a considerable time to do it.

**Comment by pauleve** [comment]
is is similar to issue #17? (you're on macOS right?)

**Comment by pauleve** [comment]
You can also give a try installing MTGO using Wine, without the Docker layer:
https://github.com/pauleve/docker-mtgo/wiki/macOS:-installing-MTGO-using-Wine
