### ISSUE TITLE
daemon error 

### ISSUE THREAD

**Issue by poppa-f** [pauleve/docker-mtgo#28]
I followed the macos steps but get the following error when I run ./run-mtgo:

(sorry if I'm being dumb, never used docker before)

> docker volume create mtgo-data
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Using network interface 'en0'
open -a XQuartz
socat on 192.168.1.3 forwarding to 
docker run --privileged --rm -e DISPLAY -v /Users/fred/.local/share/mtgo:/home/wine/.wine/host/ -v mtgo-data:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/Europe/London --name mtgo_running panard/mtgo:latest mtgo
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
./run-mtgo: line 230: 79915 Terminated: 15          tail -f ${URL_REQUESTS}
     79917                       | while read url; do
    run $WEBBROWSER "${url}";
done>

**Comment by pauleve** [comment]
As stated in the error messages, Docker does not appear to be running. You need to install it and launch it before starting run-mtgo.

**Comment by poppa-f** [comment]
yes I figured this would be the issue.

I've "brew install docker" and read the docker docs, but still not clear to
me how to actually launch docker.

Is there a step-by-step idiots guide anywhere you could point me at?

**Comment by pauleve** [comment]
https://docs.docker.com/docker-for-mac/

**Comment by pauleve** [comment]
Launching the "Docker" application should be enough. Otherwise, you can follow the step-by-step tutorial to install MTGO on macOS without Docker available here:
https://github.com/pauleve/docker-mtgo/wiki/macOS:-installing-MTGO-using-Wine
