### ISSUE TITLE
Crashes when going into "Help" menu

### ISSUE THREAD

**Issue by umeat** [pauleve/docker-mtgo#30]
The docker container crashes when accessing the "Help" menu in game. This started happening for me after the most recent update, also the game has been crashing a lot since that update.

**Comment by pauleve** [comment]
I confirm the bug, although it does not result in an actual crash, just the program stops without any clear error... @theli-ua: any known issue with Help menu with Wine without docker?

Regarding the other crashes, when do they occur? Have you done `run-mtgo --update` recently?

**Comment by theli-ua** [comment]
@pauleve iirc help will just launch a browser to open support page. But I'll recheck when I get home.

I am more interested in "crashing a lot".. At what point does it crash? 
I don't think I had game crashing ever since forever outside of gstreamer crash on start

**Comment by umeat** [comment]
There are some menus in help that launch a browser, but help itself does not. 

It's crashing midgame for me quite a lot. Since posting this, I logged into windows to play and was getting timeouts (so I guess this is due to my own network) - however in windows the timeouts bring up a dialogue box asking if I want to restart magic online, whereas it was just crashing the docker container.

**Comment by theli-ua** [comment]
It does crash for me when pressing help

**Comment by theli-ua** [comment]
I do get "sorry, your connection has failed" prompt to restart though (disconnecting from network for some time then connecting back) without crashes.

You can file a bug report on wine for the crash, but given that its such a minor issue and no apparent reason for crash it is not very likely to be looked at

**Comment by pauleve** [comment]
This is fixed with wine 5.5 (`./run-mtgo panard/mtgo:pr73`)
