### ISSUE TITLE
No window opens

### ISSUE THREAD

**Issue by stevenroose** [pauleve/docker-mtgo#32]
Hi, I'm using a perhaps non-traditional setup. I have the Awesome Window Manager and no traditional desktop manager.

When running the script, it just hands at `wine /opt/mtgo/mtgo.exe`, no windows opens or nothing else happens.

**Comment by pauleve** [comment]
Can you provide the full output for `run-mtgo`? It may look like a permission issue tu access the X server.

**Comment by stevenroose** [comment]
Oh, seems like the issue was that I wasn't in the `docker` group yet. I added me, but didn't restart. For the docker command, I could just do `newgrp docker` to refresh the terminal session, but apparently that trick didn't update it for X.

Rebooted and worked! Thanks for the quick response!
