### ISSUE TITLE
HiDPI displays

### ISSUE THREAD

**Issue by stevenroose** [pauleve/docker-mtgo#33]
I'm having a HiDPI display (4K) and the game opens extremely tiny. Does wine have a common fix for this?

**Comment by pauleve** [comment]
Have you tried https://github.com/pauleve/docker-mtgo/issues/12#issuecomment-355844711 ? (from FAQ)

**Comment by stevenroose** [comment]
Awesome!!

**Comment by brianmadden** [comment]
Note to anyone who tries to adjust the DPI for a 4k display, the maximum DPI I've been able to achieve and still open the chat window is 144. Anything higher causes the chat window to just not open, so if you've adjusted your DPI and are not seeing that chat open this may be the cause.
