### ISSUE TITLE
"Cannot locate application files on the server"

### ISSUE THREAD

**Issue by iamtomnewton** [pauleve/docker-mtgo#34]
I've just tried installing this and everything went through fine except on ./run-mtgo it boots up, opens XQuartz and throws an error box:

![screen shot 2018-06-22 at 1 17 56 pm](https://user-images.githubusercontent.com/5181414/41776290-1897b624-761f-11e8-8abc-689136e4b80e.png)

Any ideas?

**Comment by pauleve** [comment]
Have you restarted your computer? What does "Details.." says?

**Comment by iamtomnewton** [comment]
Yes I've restarted. The details opens a blank notepad. The terminal displays:

`Using network interface 'en0'
open -a XQuartz
socat on 10.171.36.81 forwarding to /private/tmp/com.apple.launchd.TEO25wEQJ5/org.macosforge.xquartz:0
docker run --privileged --rm -e DISPLAY -v /Users/newtont/.local/share/mtgo:/home/wine/.wine/host/ -v mtgo-data:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/zoneinfo/Europe/London --name mtgo_running panard/mtgo:latest mtgo
wineboot
wine /opt/mtgo/mtgo.exe
2018/06/25 08:50:18 socat[5817] E write(6, 0x7f8725002000, 64): Broken pipe
`

**Comment by pauleve** [comment]
Try reinstalling MTGO by doing `./run-mtgo --reset`
