### ISSUE TITLE
MTGO 'disconnected'

### ISSUE THREAD

**Issue by VanXodus** [pauleve/docker-mtgo#36]
My internet connection is fine but MTGO appears to be disconnected and therefore I can't log on. Updating and reseting didn't work, also I'm kinda just a noob at this stuf... any help would be appreciated!

**Comment by pauleve** [comment]
Are you on Linux or macOS?

**Comment by VanXodus** [comment]
oh sorry I forgot to mention; macOS

**Comment by pauleve** [comment]
Did it succeeded to download and install MTGO? (i.e., you reach the MTGO logging screen) If so it means the docker does have access to your internet...
Do you have any proxy or unusual network configuration? You may also to try disabling IPv6

**Comment by VanXodus** [comment]
yes, it was successfully installed and no I have any unusual network configuration as far as I know:
<img width="1280" alt="schermafbeelding 2018-07-10 om 22 21 22" src="https://user-images.githubusercontent.com/41081681/42535438-a718437c-848f-11e8-983d-912d7f238100.png">

**Comment by pauleve** [comment]
Strange. Does the "Play free trial" work?

**Comment by VanXodus** [comment]
Apparently, it does.
<img width="970" alt="schermafbeelding 2018-07-10 om 22 54 27" src="https://user-images.githubusercontent.com/41081681/42537124-4a785788-8494-11e8-8df1-bd3fd5e366a3.png">

**Comment by VanXodus** [comment]
the 'disconnected' in the lower left corner from the first picture is still present at the logging in screen though and I can't remember it being there when MTGO worked properly.

**Comment by pauleve** [comment]
So what error message appears when you enter your login and password and press login?
The "disconnected" appears for me as well until I enter my credentials.

**Comment by VanXodus** [comment]
Just turned both the router and macbook off and on again and now it seems to be working perfectly. there must have been something wrong but this did the trick. Anyway, thanks for the help and I am sorry for the inconvenience!
