### ISSUE TITLE
terminal freezes

### ISSUE THREAD

**Issue by weiyegd** [pauleve/docker-mtgo#37]
Hi guys, thanks for the great work, 

when i run the ./run-mtgo, the terminal runs for a while, and then freezes at 
System information:
    Wine build: wine-3.6
    Platform: i386
    Version: Windows 7
    Host system: Linux
    Host version: 4.9.87-linuxkit-aufs

after a long time waiting, i have to ctrl+c to kill it.

and obviously, run-mtgo doesn't work.

what should i do? thank you:)

**Comment by pauleve** [comment]
Try with
```
./run-mtgo --reset
```
and send the full output here

**Comment by weiyegd** [comment]
Hi, I restarted the terminal, and then everything works fine, thank you!
