### ISSUE TITLE
run.mtgo crashes when installing

### ISSUE THREAD

**Issue by 101091** [pauleve/docker-mtgo#38]
i get this after clicking Accept on the EULA prompt:

<img width="414" alt="screen shot 2018-07-16 at 11 25 40 am" src="https://user-images.githubusercontent.com/41304618/42776196-290b2e3a-88eb-11e8-8682-5c8383460e59.png">

here are the program error details. sorry, i had to take screenshots in chunks because i have no idea how to save it as a .txt, and it wouldn't let me copy and paste the text.

<img width="691" alt="screen shot 2018-07-16 at 11 31 03 am" src="https://user-images.githubusercontent.com/41304618/42776534-271af654-88ec-11e8-8d78-be36fd8856d3.png">

<img width="691" alt="screen shot 2018-07-16 at 11 31 37 am" src="https://user-images.githubusercontent.com/41304618/42776537-2b382b62-88ec-11e8-9ccb-ef26c5ca6482.png">

<img width="691" alt="screen shot 2018-07-16 at 11 32 14 am" src="https://user-images.githubusercontent.com/41304618/42776545-2ea432dc-88ec-11e8-90d3-f464e7490c73.png">

**Comment by pauleve** [comment]
Can you try with
```
./run-mtgo --reset panard/mtgo:2018-04-20
```
and also send the output of the terminal?

**Comment by dehli** [comment]
I also experienced this issue using Linux as the host. Trying the second command `./run-mtgo --reset panard/mtgo:2018-04-20` I was able to install it.
