### ISSUE TITLE
Pulse Audio locks up on launching

### ISSUE THREAD

**Issue by JeffHoogland** [pauleve/docker-mtgo#39]
Pulse audio kept hard locking on my system, and I finally figured out that launching MTGO under this docker image was the cause. After launching with --disable-sound pulse audio no longer locks, so pretty certain launching MTGO with the default settings from here is the cause

Screenshot of pulse audio in my system manager when it is locked up: https://i.imgur.com/fowS4Ke.png

Also worth noting I don't seem to be able to re-enable sound after running with --disable-sound. Running with the --sound option gives me:

    PulseAudio does not seem active (/run/user/0/pulse/native not found)

**Comment by pauleve** [comment]
Thanks for this report.
Just to get it right - now if you do `./run-mtgo` with the latest version of the script (https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo) without any option, is PulseAudio still overheating? Or did running once with `--disable-sound` fixed the issue?
For re-enabling sound, currently the script does not autostart pulseaudio, so you'll need doing `pulseaudio --start` just before calling `./run-mtgo --sound`.

**Comment by JeffHoogland** [comment]
pulseaudio --start before running with --sound doesn't seem to change anything:

    jeff@hoogl-desktop:~$ pulseaudio --start
    jeff@hoogl-desktop:~$ sudo ./run-mtgo --sound
    PulseAudio does not seem active (/run/user/0/pulse/native not found)

Just for my own understanding - when I run this script with --disable-sound is that only toggling audio off for the docker image / MTGO or is this doing something at the system level?

**Comment by pauleve** [comment]
Ah, this is due to the sudo, the script looks for pulseaudio running for the root user in this case..
Why do you need sudo by the way? If this is to run docker, it is usually sufficient to add your user to the docker group (`sudo usermod -aG docker $USER`, then restart session).

The `--disable-sound` only acts within the docker image (disable the audio driver in wine). So does `--sound` as well, in theory..

**Comment by JeffHoogland** [comment]
Ahh alrighty, I'll have to setup my normal user to have docker permission when I get a chance. I'd never poked at docker before this, so when it didn't work with my normal user by default I just ran it with sudo and have been using it as such since cause it just worked that way.

**Comment by pauleve** [comment]
As for issue #40, you will also have to restore the right permissions in your ~/.local/share/mtgo
(`sudo chmod -R $USER: $HOME/.local/share/mtgo`)

**Comment by pauleve** [comment]
Closing old and probably outdated bugs. Please reopen if it is still happening.
