### ISSUE TITLE
oci runtime error

### ISSUE THREAD

**Issue by norg** [pauleve/docker-mtgo#4]
I'm trying to get this running on my ArchLinux x86_64 installation but I run into this error:

`
docker run --privileged --rm -it -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /root/.Xauthority:/home/wine/.Xauthority:ro --net=host --ipc=host -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro --name mtgo_running panard/mtgo:latest mtgo
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/etc/timezone\\\" to rootfs \\\"/var/lib/docker/devicemapper/mnt/825a5ce6a14819bdc0dbc1b5aebc009f5c3d6745167c255c0b0ef743afad268e/rootfs\\\" at \\\"/var/lib/docker/devicemapper/mnt/825a5ce6a14819bdc0dbc1b5aebc009f5c3d6745167c255c0b0ef743afad268e/rootfs/etc/timezone\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
`

On which distro did you run it?
I got it working on Ubuntu 16.04 LTS but I prefer to have it running on my Workstation :)  And shouldn't be the issue with the multimonitor setup I guess.

**Comment by pauleve** [comment]
This is an issue with the way distros deal with timezone/localtime. I modifiied run-mtgo so it does no try to mount /etc/localtime and /etc/timezone if they are not plain files.
The full fix will be tracked by issue #5
