### ISSUE TITLE
Start up crash on Linux Mint

### ISSUE THREAD

**Issue by petehead** [pauleve/docker-mtgo#40]
So, I'm very new to using Linux and running things out of Terminal etc but I've been having an issue where I run the script, where it appears to start, then crashes, and I lose sound on my system. The terminal outputs the following : 

` $ sudo ./run-mtgo
[sudo] password for peter: 
docker run --privileged --rm -e DISPLAY -v /home/peter/.local/share/mtgo:/home/wine/.wine/host/ -v mtgo-data:/home/wine/.wine/drive_c/users/ -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /home/peter/.Xauthority:/home/wine/.Xauthority:ro --net=host --ipc=host -e TZ=/usr/share/zoneinfo/Australia/Sydney --name mtgo_running panard/mtgo:latest mtgo
wineboot
wine /opt/mtgo/mtgo.exe
====== MTGO.exe has started.
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: Permission denied

ERROR: Caught a segmentation fault while loading plugin file:
/usr/lib/i386-linux-gnu/gstreamer-1.0/libgstcoreelements.so

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.

(wine:95): GStreamer-CRITICAL **: gst_pad_unlink: assertion 'GST_IS_PAD (srcpad)' failed

(wine:95): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(wine:95): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
====== shutting down
wineserver -kw
./run-mtgo: line 234:  3674 Terminated              tail -f ${URL_REQUESTS}
      3675                       | while read url; do
    run $WEBBROWSER "${url}";
done`

I honestly have no damn idea what this means. It's probably a rather simple error and fix, but this a brave new world for me, was hoping someone could shed some light on it for me.

**Comment by petehead** [comment]
Running without sound appears to fix the issue! Thanks mate. I've added myself to the docker group, but attempting to run without sudo just gives the following: 

./run-mtgo: line 230: /home/peter/.local/share/mtgo/openurl: Permission denied

**Comment by pauleve** [comment]
Good to hear. I've updated the image so the default behaviour disable sound, thank you for the report.

For the permission issue, doing
```
sudo chmod -R 1000: /home/peter/.local/share/mtgo
```
should fix it.
