### ISSUE TITLE
Unable to run without Sudo

### ISSUE THREAD

**Issue by petehead** [pauleve/docker-mtgo#41]
So I've been having issues on and off with MTGO under Linux. Have just purged all MTGO related content and reinstalled the script, made myself a member of the docker group etc however, when I attempt to run the scrip without sudo I get the following:

`./run-mtgo: line 270: /home/peter/.local/share/mtgo/openurl: Permission denied`

Again, I'm not super familiar with the world of linux yet, so I'm really unsure as to what I should be doing here. 

Cheers for any help!

**Comment by GustavoRSSilva** [comment]
@petehead what happens when you use the command ``` docker images ```  vs ```sudo docker images ``` ?

You need [to follow this steps](https://docs.docker.com/install/linux/linux-postinstall/) in order to remove the necessity of using the sudo with docker

**Comment by kyletsavage** [comment]
I'm having the same issue. I can run `docker images` and `docker run hello-world` without needing sudo.

But when I try `./run-mtgo` I get "bash: ./run-mtgo: Permission denied"

I have already created the docker group and added myself to it.

**Comment by kyletsavage** [comment]
I have, and that gives no errors, but then I still get the permission
denied error

**Comment by pauleve** [comment]
This is probably because you ran with sudo initially - to fix the permissions, you can either do `./run-mtgo --reset` or 'sudo chown -R peter /home/peter/.local/share/mtgo`

**Comment by pauleve** [comment]
```
sudo rm -rf /home/peter/.local/share/mtgo
./run-mtgo
```
Please copy&paste the full output of these commands if it still doesn't work

**Comment by kyletsavage** [comment]
savage@savage-System-Product-Name:~$ sudo rm -rf
/home/savage/.local/share/mtgo
[sudo] password for savage:
savage@savage-System-Product-Name:~$ ./run-mtgo
bash: ./run-mtgo: Permission denied
savage@savage-System-Product-Name:~$ ^C
savage@savage-System-Product-Name:~$

**Comment by pauleve** [comment]
`chmod 755 run-mtgo` should do it.

**Comment by pauleve** [comment]
Good to hear.
From what I understood of the different messages, you probably ran initially `sudo ./run-mtgo` ; that created internal files, including `.local/share/mtgo/openurl` with permissions for root user. Then, when running without sudo your regular user does not have the permissions to run the openurl script. As for the permission denied for `run-mtgo`, each time you download the script you need to redo the `chmod +x ./run-mtgo` to be able to execute it.
