### ISSUE TITLE
Crashes on Foil Cards Sometimes

### ISSUE THREAD

**Issue by JeffHoogland** [pauleve/docker-mtgo#45]
Non-zero chance this is a MTGO "Feature" but I am getting crashes when foil cards are displayed a non-zero amount of the time. Anyone else?

**Comment by JeffHoogland** [comment]
Think it might be a Wine issue? Seeing this in Terminal when it dumps on a foil:

006d:err:mmdevapi:DllGetClassObject Driver initialization failed
006d:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
006d:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
006d:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
006d:err:quartz:GetClassMediaFile Media class not found

**Comment by pauleve** [comment]
Never happened with me, but I'm not an intensive player.. Do you have any way to trigger the bug almost surely, or does it appear to be  random?
Do you have foil animation enabled? If yes, maybe try disabling it.
Also, are you using the latest run-mtgo script and docker image? (`./run-mtgo --update` with latest script).

**Comment by JeffHoogland** [comment]
It is inconsistent sadly. Foil animations are off. Only crash I have though has to do with foils being involved. Running the latest version of the image.

**Comment by pauleve** [comment]
Ok.. I will try spending some time with bots selling foil cards to see if I can reproduce it here...
It may be worth opening a bug on bugs.winehq.org.

**Comment by pauleve** [comment]
Closing old and probably outdated bugs. Please reopen if it is still happening.
