### ISSUE TITLE
Cannot Run on Deepin 15.6

### ISSUE THREAD

**Issue by blurmcclure18** [pauleve/docker-mtgo#46]
I tried following the instructions as best I can but when I run ./run-mtgo I am getting an error. Also when going through the walkthrough run first running ./run-mtgo it fails to create a docker volume. docker volume create --name mtgo-data-(user) does work though. After adding myself to the docker group and running ./run-mtgo I get this output:

docker run --privileged --rm -e DISPLAY -v mtgo-data-alec:/home/wine/.wine/host/ -v mtgo-data-alec:/home/wine/.wine/drive_c/users/ -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /home/alec/.local/share/mtgo/Xauthority:/home/wine/.Xauthority:ro --net=host --ipc=host -e TZ=/usr/share/zoneinfo/America/Chicago --name mtgo_running panard/mtgo:latest mtgo
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:53: mounting \\\"cgroup\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/dd253bd177fcdd4ea577a0d00208588e6134d6a83d49f084e2611190a4362ee6\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"no subsystem for mount\\\"\""n".

EDIT: I fixed the not running issue, but I don't know how to enable sound for the application. I installed PulseAudio but don't hear anything when the application runs/opens.

**Comment by pauleve** [comment]
Sound is currently not working.. if it is important for you, consider subscribing to issue #8 to follow the updates.
