### ISSUE TITLE
After GRN update UI glitches

### ISSUE THREAD

**Issue by michalkaftanski-airhelp** [pauleve/docker-mtgo#48]
After GRN client update can't continue due to UI glitches - impossible to accept updated Rules&Terms. Found on latest docker-mtgo, MacBook Pro (Retina, 13-inch, Early 2015), HighSierra 10.13.6.

**Comment by pauleve** [comment]
I've updated the image to include latest wine version ; can you try with `./run-mtgo --update`?

**Comment by pauleve** [comment]
Thanks for the feedback - good to know about the workaround. Maybe that using --winecfg option to tick "emulate desktop" option in the Graphics tab might also help..

**Comment by theli-ua** [comment]
@pauleve  does docker image set ddr=gdi for the wine prefix?
I'm not using docker image but some time ago noticed that I had UI rendering issues with MTGO unless I force that.

**Comment by HankMD** [comment]
@pauleve I was also experiencing this issue. Both the `--reset` option and using the `--winecfg` option to tick "emulate desktop" seem to both work.

**Comment by pauleve** [comment]
From what I understood, wine should select GDI by default as there is no OpenGL/directX capability in the Docker image. But I just pushed an image with wine 3.20 with an explicit ddr=gdi call.
You can try with `./run-mtgo --update`; let me know if it happens again..
