### ISSUE TITLE
More generic timezone detection

### ISSUE THREAD

**Issue by pauleve** [pauleve/docker-mtgo#5]
Currently we rely on /etc/timezone and /etc/localtime files to forward the correct time to the container.
It seems that some distributions (and probably Mac OS X) use different pathways to set the timezone.
The script `run-mtgo` should be able to auto-detect most of them.

**Comment by apetresc** [comment]
Can confirm the new `run-mtgo` script now works without any modification on my Arch box :)

**Comment by norg** [comment]
Same for me, thanks a lot!
