### ISSUE TITLE
0075:fixme:thread:NtGetCurrentProcessorNumber need multicore support (4 processors) 

### ISSUE THREAD

**Issue by DanteZ5** [pauleve/docker-mtgo#50]
Hello Paul,

I've this issue by following your tutorial.
on terminal : repetitive information like this 
0075:fixme:thread:NtGetCurrentProcessorNumber need multicore support (4 processors)

What I have on screen (file joined) but I can't have any action.

<img width="947" alt="capture d ecran 2018-10-12 a 16 03 59" src="https://user-images.githubusercontent.com/11738628/46874125-acf49280-ce38-11e8-924e-cbd984605ae8.png">
#
Thank you for your support :)

**Comment by pauleve** [comment]
the terminal information is harmless.
You mean that if you scroll until the end of the term, the I accept button does'nt activate?

**Comment by DanteZ5** [comment]
hello,
I meant it was impossible to scroll down until I try multiple alt-tab, then I succeed to go to the next step. But at the end, black screen and loop in the terminal with the information ahead.

**Comment by pauleve** [comment]
So is it like in issue #37 ? You can try doing `xrefresh` in the XQuartz Xterm, but this is a currently known bug on some macOS configurations.

**Comment by pauleve** [comment]
Ok, sorry it is #17 !
