### ISSUE TITLE
"EULA file not found"

### ISSUE THREAD

**Issue by franklee77** [pauleve/docker-mtgo#54]
This has been running wonderfully in my Ubuntu 18.04. After the latest MTGO update (3.4.106.2058), I am seeing the following error: MTGO runs and the login screen appears, but then when the EULA window pops up I see a "EULA file now found" error. I cannot accept the new EULA and the program shuts down. Is anybody else seeing this issue?

**Comment by mplozza** [comment]
I'm experiencing the same issue.

**Comment by pauleve** [comment]
Running the following command should fix it, assuming `.wine` is your wine prefix:
```
find .wine/drive_c/ -name 'EULA_en.rtf' -exec sed '/^{\\pict/,/^}/ d' -i "{}" \;
```

I've pushed a Docker image which includes this hotfix (`./run-mtgo --update`).
Note that it requires to quit MTGO and start again so the EULA file can be fixed after the update.

**Comment by pauleve** [comment]
Bug reported upstream: https://bugs.winehq.org/show_bug.cgi?id=46287

**Comment by franklee77** [comment]
Thank you so much for this - you're truly doing a great service to the community!

**Comment by rcbm** [comment]
For whatever reason I can't seem the workaround to fix the issue for me. Perhaps its because when I do a straight `find ~/.wine/drive_c/` I don't see a file named `EULA_en.rtf` listed at all, so it isn't available to have the pic block removed? Where should the file normally live? And does anyone have a copy of their old version or could I just add any richtextfile there?

**Comment by theli-ua** [comment]
As I've summarized in the linked bug this can be worked around by using native gdiplus. 
Though I have not tested if it causes any other issues

**Comment by johnmain** [comment]
I just installed from scratch and I am getting the Missing EULA error.

**Comment by mitermayer** [comment]
The bug seems to still happen on linux even after doing a "./run-mtgo --update"

**Comment by pauleve** [comment]
You need to `./run-mtgo` twice in order to fix the licence file. I'll integrate the native gdiplus in the next docker image.

**Comment by pauleve** [comment]
The latest image includes native `gdiplus`, therefore `./run-mtgo --update` should no longer requires a double run to fix the EULA file.
