### ISSUE TITLE
Occasional clicks switch windows

### ISSUE THREAD

**Issue by MichaelEvans** [pauleve/docker-mtgo#55]
I'm using the Wine instructions on OS X and occasionally clicking will switch windows (i.e. the game screen disappears and switches to whatever was behind it. I can't quite isolate _when_ these clicks occur but it's fairly frequent. Any ideas? Not sure how to triage this.

**Comment by MichaelEvans** [comment]
How do I access this configuration if I'm using the instructions from here (https://github.com/pauleve/docker-mtgo/wiki/macOS:-installing-MTGO-using-Wine)? I'm not using the ./run-mtgo command - should I be?

**Comment by pauleve** [comment]
Then you should run `winecfg`.

**Comment by jfabre** [comment]
I have the same issue and winecfg emulate desktop didn't do it for me. 
It wasn't doing that before, seems to be related to the mtgo patch that came with the eula bug.
It's either that or mojave update for me, those are the only 2 changes that happened on my machine.

**Comment by MichaelEvans** [comment]
Another data point - `winecfg` didn't fix this for me, but it did happen pre-EULA and happens on pre-Mojave for me.

**Comment by jfabre** [comment]
@MichaelEvans What version of Wine devel are you on?
I just changed to wine-4.0-rc2 very recently.

**Comment by MichaelEvans** [comment]
@jfabre Same, upgraded in an attempt to fix this issue. Even tried Staging.

**Comment by pauleve** [comment]
To test if this is due to the patch, could you try with the previous version of the Docker image? (without the patch, but as you accepted the licence it doesn't matter):
```
./run-mtgo panard/mtgo:2018-11-19
```
Keep me posted

**Comment by jfabre** [comment]
I think you understood wrong, I meant the MTGO patch (eula). I think we're both not using the docker image to run mtgo. What's the advantage to run the docker image over just running it straight from wine?
The first time I tried the image, it was so slow on my machine it was practically unplayable.
I do run a ubuntu server that's much more powerful, is there any way I could run the docker image there and render everything on my laptop?

**Comment by pauleve** [comment]
Ah right so the "patch" is not the issue as it just modified the license file.

**Comment by jfabre** [comment]
I was talking about the mtgo update as the "patch" that triggered the eula bug.

**Comment by jfabre** [comment]
@MichaelEvans, I think I figured out a fix. went to winecfg -> graphics unchecked everything AND checked emulate desktop (to a 1024x768 don't think it matters, but just in case). The window switching bug doesn't seem to occur anymore. Only played one game, but you might want to try this.

It might be unchecking everything or both unchecking and checking emulate I'm not sure, but it doesn't seems to switch window anymore.

**Comment by pauleve** [comment]
The latest devel version of wine (4.16) includes some patches which should improve the focus handling. Let me know if updating to the latest image fixes the issue (`./run-mtgo --update`).

**Comment by pauleve** [comment]
The default image now ships wine 5.5 which includes a lot of fixes related to focus issues.
Let me know if you still experience this bug after `./run-mtgo --update`
