### ISSUE TITLE
MTGO unable to connect to the internet

### ISSUE THREAD

**Issue by kylesnowschwartz** [pauleve/docker-mtgo#61]
Hi there! Firstly thank you so much for docker mtgo, I've been using it with almost no issues for months and months. I've run into a stumbling block this evening I can't seem to just 'restart' my way out of.
![error](https://user-images.githubusercontent.com/11069001/58953468-b4631480-87ea-11e9-982a-7e4779d3e9ee.png)

As you can see, when I try to login I receive this error message. I've tried restarting my computer, running `./run-mtgo --reset` and `./run-mtgo --update` which tells me I have the latest version. Before it was working fine, but my computer had gone to sleep and MTGO usually loses connection but doesn't know it when I wake up my computer. So I closed the program and restarted the docker container, which is when I encountered the message.

I've added a text file with the terminal output, in case that helps
[terminal-output.txt](https://github.com/pauleve/docker-mtgo/files/3256960/terminal-output.txt)

Thanks for any help you might be able to provide,
Kyle

**Comment by pauleve** [comment]
When had this happened? Because MTGO is currently in downtime until noon PT..

**Comment by kylesnowschwartz** [comment]
Oh. My bad.

:)
