### ISSUE TITLE
EULA not found MacOSX

### ISSUE THREAD

**Issue by shawn-ant** [pauleve/docker-mtgo#63]
Tried the fixes nothing seems to work.  Can only click 'Decline' at the EULA screen. (pre login)

 I'm new to Wine so its possible I misunderstand the lingo involving the fix.

Shawns-MacBook-Pro:~ shawnanthony$ wine mtgo.exe
0084:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
0084:fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
0084:fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
0084:fixme:advapi:GetWindowsAccountDomainSid (0x32e5d0 0x199e84 0x32e5e8): semi-stub
0084:fixme:secur32:GetComputerObjectNameW NameFormat 7 not implemented
0084:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
0085:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv4 not supported in this platform
0084:fixme:ntdll:EtwEventRegister ({319dc449-ada5-50f7-428e-957db6791668}, 0x10021925, 0x1006dbd0, 0x1006dbe8) stub.
0084:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x10002f3d, 28) stub
0084:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040154 for dll L"mscoree.dll"
0084:err:ole:CoGetClassObject no class object {1e66f26b-79ee-11d2-8710-00c04f79ed0d} could be created for context 0x1
0084:fixme:ntdll:EtwEventUnregister (deadbeef) stub.

**Comment by pauleve** [comment]
You mean you have tried both doing
```
winetricks gdiplus gdiplus=native
```
and 
```
find ~/.wine*/drive_c/ -name 'EULA_en.rtf' -exec sed -e '/^{\\pict/,/^}/ d' -ibck "{}" \;
```
?
What is the output of
```
find ~/.wine*/drive_c/ -name 'EULA_en.rtf' 
```
Which version of wine are you using?
May be related to #63 - but I cannot reproduce the error..

**Comment by shawn-ant** [comment]
the output is:

Shawns-MacBook-Pro:~ shawnanthony$ find ~/.wine*/drive_c/ -name 'EULA_en.rtf'
/Users/shawnanthony/.wine/drive_c//users/shawnanthony/Local Settings/Application Data/Apps/2.0/HPKLW8B2.LL9/8XNQ64DZ.XQY/mtgo.exe_98ecb8aa8cf73f16_0003.0004_none_c9eab8e0944c8cc3/EULA/EULA_en.rtf
/Users/shawnanthony/.wine/drive_c//users/shawnanthony/Local Settings/Application Data/Apps/2.0/HPKLW8B2.LL9/8XNQ64DZ.XQY/mtgo..tion_98ecb8aa8cf73f16_0003.0004_68472e39335f73e8/EULA/EULA_en.rtf

I'm using wine 4.0

**Comment by pauleve** [comment]
for winetricks, it depends on how downloaded it ; see (4) at https://github.com/pauleve/docker-mtgo/wiki/macOS:-installing-MTGO-using-Wine#first-installation
maybe in your case it is `./winetricks gdiplus gdiplus=native`

I don't have access to macOS until a couple of day; I'll give a try then.

If you are using wine only for MTGO, you may try from a fresh start (`rm -rf ~/.wine`) and redoing the installation instructions from `wineboot`command.

**Comment by shawn-ant** [comment]
./winetricks was accepted and it ran something.  Unfortunately it didn't solve the EULA issue upon MTGO startup.

I'm going to try the fresh start next

**Comment by shawn-ant** [comment]
Unfortunately now I think I completely ruined it by trying to reset.  I think I might have to try and completely remove it from my system and try again since the original installation doesn't really work anymore

**Comment by pauleve** [comment]
Good to hear :-) that's strange though, let me know if it happens again (re-open this issue)
