### ISSUE TITLE
Maybe wrong version of MTGO?

### ISSUE THREAD

**Issue by Rango77** [pauleve/docker-mtgo#67]
Hi all,

I was able to open MTGO by following the instructions, build a deck, and play a game successfully. However, this version is not as described by any recent MTGO new player guides/videos on the web. The WOTC website and these guides describe tabs on the top that say Home, Collection, Play Lobby, Store, Trade, Account, and Help. Mine only has 4 tabs, including Collection, Constructed, and Help.
Additionally, I cannot find many of the features described in these guides, such as Solitaire play mode.
Is this an outdated version? Did I do something wrong?
Thank you.

**Comment by pauleve** [comment]
There is no choice but running the latest version of MTGO. For the features, maybe the documentation is outdated. For the tabs, it might be a resolution issue, see https://github.com/pauleve/docker-mtgo/issues/12#issuecomment-355844711 to adjust it
