### ISSUE TITLE
Bump Wine version to 2.18-staging vanilla

### ISSUE THREAD

**Issue by apetresc** [pauleve/docker-mtgo#7]
At least one of Anton's patches has been merged into 2.16 which has just been added to wine-staging: https://www.winehq.org/announce/2.16 (`windowscodecs: PNGEncoder: Return 32bppRGBA pixel format by default.`)

**Comment by theli-ua** [comment]
thats a good one - it finally makes mana cost/set symbols have transparent background when rendering cards

**Comment by pauleve** [comment]
The current docker image already includes these patches (it has been created a bit before 2.16 release, but was including all the important patches).
But I'll update the wine docker image soon anyway.

**Comment by pauleve** [comment]
Done (almost 2.17). Let me know if you have any trouble with the updated image.

**Comment by pauleve** [comment]
Docker image `panard/mtgo:2017-09-19` (`latest`) is now based on 2.17 staging + https://github.com/theli-ua/wine/tree/df836c6d6f449836e969fe5ed2fd69ba3381c55e
(commit 8ce3fe3)

**Comment by theli-ua** [comment]
since all necessary patches have been accepted now, you can switch to master (+staging for decoding certain images bug) or wait till 2.18

**Comment by pauleve** [comment]
Thanks for the info, I'll wait until 2.18 and use the official wine-staging 2.18 package.
