### ISSUE TITLE
Can not login.

### ISSUE THREAD

**Issue by wfx** [pauleve/docker-mtgo#77]
Hi,
MTG Arena do start but i cant login with my user and password.
I double check it. I use the right one but no luck.

Maybe this error line helps:
011b:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

thx a lot

**Comment by pauleve** [comment]
Are you referring to MTG *Arena* or Magic Online? This project is focused only on MTGO, not Arena.

**Comment by wfx** [comment]
😀, sorry my fault.
