### ISSUE TITLE
Security Question: Where is the source/Dockerfile for "panard/wine:custom"?  

### ISSUE THREAD

**Issue by ahungry** [pauleve/docker-mtgo#78]
First off, I love and appreciate that this exists (thank you!)

However, every time I "run-mtgo", I feel a little nervous, as I'm essentially transmitting credit card info into a Docker image for which I do not have the source/cannot build entirely on my own.

If someone were to compromise the panard docker hub account and change panard/wine:custom tag, it would be very easy to include a key logger + remote transmission that the user doesn't realize is running while they execute wine.

Could I build my own "source" wine to use in combination with this project's Dockerfile?

**Comment by valentin-nasta** [comment]
@ahungry sure, you can find the source for the panard/wine here: https://github.com/pauleve/docker-mtgo/blob/master/docker-wine/Dockerfile

**Comment by pauleve** [comment]
You can build the full stack of  Docker images using `make TIMESTAMP=latest` from this git repository.

**Comment by ahungry** [comment]
Thanks everyone!
