### ISSUE TITLE
Problem with Docker and window/driver

### ISSUE THREAD

**Issue by somethingstranger** [pauleve/docker-mtgo#80]
Hi Loïc,

Thanks for all the work you do on this project! I'm having a problem running ./run-mtgo. Here's the final error message before it just stops doing anything, though still running:

"0047:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0047:err:winediag:nodrv_CreateWindow The explorer process failed to start.
0047:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0047:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0047:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0"

I can also post the full output. Really appreciate the help.

Dash

**Comment by somethingstranger** [comment]
I restarted my computer and am no longer having the issue. Will update if anything doesn't work.

**Comment by newfiepro** [comment]
I restarted my computer and still not working. getting a different though I believe

**Comment by somethingstranger** [comment]
Newfie, there's another error going around related to libraries and the recent MTGO update.

**Comment by newfiepro** [comment]
I only just started using this 2 days ago so fairly new, are people usually able to find the solution? I know nothing about this stuff

**Comment by pauleve** [comment]
It maybe related to #79 as recent upgrade seems to break the current Docker image
