### ISSUE TITLE
Error `Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"`

### ISSUE THREAD

**Issue by Uzay-G** [pauleve/docker-mtgo#81]
Hey! I had started using this image since yesterday and everything was working fine but since a few hours ago it stopped working. The new error I am getting is `Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"`. Does anyone know how I can fix this?

I am using Ubuntu by the way.

Thanks!

**Comment by pauleve** [comment]
Duplicate of #79
