### ISSUE TITLE
Cannot Open MTGO Docker Image

### ISSUE THREAD

**Issue by Rango77** [pauleve/docker-mtgo#82]
Hi,

When I open the README instructions for how to install the MTGO Cocker image, I installed the docker software, xquartz, socat, gnu-getopt, and wget wihtout issue. 
I inputted 

curl -o run-mtgo https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo 

after restarting my session, which yielded

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8201  100  8201    0     0  15679      0 --:--:-- --:--:-- --:--:-- 15680

Then I attempted 

chmod +x run-mtgo

When I entered this, I got

chmod: run: No such file or directory
chmod: mtgo: No such file or directory

Thanks for the help!

**Comment by pauleve** [comment]
for the chmod command make sure you enter "run-mtgo" (with - being regular dash), as sometime copy paste of dash symbol is messed up on macOS

**Comment by Rango77** [comment]
Entered: chmod +x run-mtgo(no copy and paste)

The terminal did nothing, it went to the next line awaiting another command, which is what it would do if I pressed enter without inputting anything. Super weird.

**Comment by pauleve** [comment]
can you paste a screenshot?

**Comment by Rango77** [comment]
Last login: Sat Mar 28 16:40:57 on ttys000
_____-iMac:~ _____$ curl -o run-mtgo https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8201  100  8201    0     0  15679      0 --:--:-- --:--:-- --:--:-- 15680
_____-iMac:~ _____$ chmod +x run mtgo
chmod: run: No such file or directory
chmod: mtgo: No such file or directory
_____-iMac:~ _____$ chmod +x run-mtgo
_____-iMac:~ _____$

**Comment by Rango77** [comment]
Doin it this way with _____ where my name is.

**Comment by pauleve** [comment]
so the last chmod worked correctly. now type (with copy-pasting) `./run-mtgo`

**Comment by Rango77** [comment]
docker volume create mtgo-data-_____
./run-mtgo: line 123: docker: command not found

**Comment by pauleve** [comment]
Yes you need to install docker

**Comment by Rango77** [comment]
Ah, I had to open Docker. It now appears installed and running.
Still, I input the command 

chmod +x run_mtgo

and got

chmod: run_mtgo: No such file or directory

**Comment by Rango77** [comment]
Oh lol relized as I sent had _ not -

**Comment by Rango77** [comment]
Input:  chmod +x run-mtgo
Nothing happened, just skipped a line.

**Comment by pauleve** [comment]
chmod shows nothing on success; please follow the README and continue with run-mtgo

**Comment by Rango77** [comment]
It opened! Yes:) I will continue with the other thread to solve the original problem now.
Thanks for the time.
