### ISSUE TITLE
MTGO has encountered a serious problem and needs to close

### ISSUE THREAD

**Issue by newfiepro** [pauleve/docker-mtgo#86]
Ever since the newest fix I occasionally will receive a message that MTGO has encountered a serious problem and needs to close. It says the problem may be with MTGO or with wine. The first time it happened I closed the program, restarted it and got the message again before restarting my computer and it worked no problem. Today I got the problem twice while trying to search for a game and then 3 times as it was trying to log me in despite closing everything and shutting off the computer between each time. I keep trying as I rent cards and am in the middle of a league so need to finish it before returning them. I'm on macOS. Not sure if anyone else has had this problem.

**Comment by newfiepro** [comment]
The next time it happens I'll post more info about what specifically it says

**Comment by newfiepro** [comment]
The program MTGO.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience. 

This could be caused by a problem in the program or a deficiency in Wine. You may want to check the Application Database for tips about running this application.

**Comment by pauleve** [comment]
Please copy and paste the full output of the following command until crash:
```
./run-mtgo --update
```

**Comment by pauleve** [comment]
(and if you are not using docker, try with the latest wine staging available at https://dl.winehq.org/wine-builds/macosx/pool/winehq-staging-5.5.pkg)
