### ISSUE TITLE
MTGO static images take a while to appear, prompt box issues

### ISSUE THREAD

**Issue by willyem** [pauleve/docker-mtgo#90]
system: macos Mojave, 10.14.6 

currently trying to run MTGO using the following command: 

```
./run-mtgo panard/mtgo:2020-03-30
```

mtgo loads and begins to run, though overall response is slow; whenever graphics are meant to appear, it can take a while for the image to show up; in the case of prompt boxes (i.e. double clicking on a pack to open it), a garbled box appears on screen and the mouse has to be hovered over it in order for the individual buttons to begin to appear. 

<img width="621" alt="Screen Shot 2020-04-17 at 11 41 28 AM" src="https://user-images.githubusercontent.com/10605674/79603155-a6d01980-80a0-11ea-9922-3eb7eacd8a4b.png">

**Comment by pauleve** [comment]
On macOS, Dokcer is running within a virtual machine, which slows things considerably, and has issue with display (see #17).
You should consider installing wine directly, following https://github.com/pauleve/docker-mtgo/wiki/macOS:-installing-MTGO-using-Wine

**Comment by willyem** [comment]
@pauleve thanks for the response! 

unfortunately, I think my wine installation is completely busted -- I had it up and running perfectly on my laptop a few months ago, but I recently updated the OS and it seems like it all got thrown out of whack. I'll refer to other issues to describe these problems, however, and try to use other methods for trouble shooting. 

thanks!

**Comment by pauleve** [comment]
You may try deleting your wine directory and reinstall everything properly (`rm -rf ~/.wine*`); keep me in touch
