### ISSUE TITLE
Unable to install/run MTGO on wine. Hangs on "verifying application requirements"

### ISSUE THREAD

**Issue by maxiewawa** [pauleve/docker-mtgo#93]
I'm installing wine according to the guide: https://github.com/pauleve/docker-mtgo/wiki/macOS:-installing-MTGO-using-Wine

When I get to step 5, the "verifying application requirements" that usually comes when running MTGO appears, but never disappears.

When I try the steps 5, 6 and 7 the same thing occurs.

In step 3, I'm not prompted to install mono or gecko, maybe because I've installed them already. The same with .Net.

Please let me know if you need the entire output or any screenshots of any of the steps.

Thanks very much!

EDIT: Left it for a few hours, just in case, and it's still "Verifying Application requirements." My Terminal is telling me "0067:fixme:thread:NtGetCurrentProcessorNumber need multicore support (4 processors)".

**Comment by pauleve** [comment]
Closing old inactive bugs. Feel free to re-open if still occurring.
