### ISSUE TITLE
MTGO freezes with "Too many open files" message in terminal

### ISSUE THREAD

**Issue by awjackson** [pauleve/docker-mtgo#97]
A few seconds after logging in, the MTGO client always freezes with the last message in the terminal window as follows:

0067:err:winediag:FILE_CreateFile Too many open files, ulimit -n probably needs to be increased

**Comment by pauleve** [comment]
Try doing `ulimit -n 4096` and start again the client.
What is your operating system? Are you using the `./run-mtgo` script (Docker), or direct wine installation?

**Comment by awjackson** [comment]
I'm using the Docker installation, on Fedora 32.

If I run-mtgo --shell and then try the ulimit command, I get "cannot modify limit: Operation not permitted". I assume I need the root password for the OS inside the container.

**Comment by awjackson** [comment]
Well, I've solved the problem. There's a default-ulimit setting in /etc/sysconfig/docker, which I changed from 1024 to 8192, and now MTGO works. Apparently Fedora recently added this setting to their packaging of docker.

**Comment by pauleve** [comment]
Thanks for the tip. The uname command could probably have been executed before the run-mtgo command (outside docker) . But changing the default is indeed a more persistent solution.

**Comment by awjackson** [comment]
Containers have their own ulimit variables that are separate from the host OS. Red Hat recently set the default open file limit inside containers to 1024 to fix [this issue](https://bugzilla.redhat.com/show_bug.cgi?id=1715254) (apt-get thrashing)
